// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

namespace Eclypses.MTE {
  /// <summary>
  /// Interface MteFlenEnc
  ///
  /// This is the MTE fixed-length add-on encoder.
  /// </summary>
  public interface IMteFlenEnc : IMteCore {
    /// <summary>
    /// Returns the encode buffer size in bytes.
    /// </summary>
    int GetBuffBytes();

    /// <summary>
    /// Returns the encode buffer size in bytes.
    /// </summary>
    int GetBuffBytesB64();

    /// <summary>
    /// Encode the given data. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    byte[] Encode(byte[] data, out MteStatus status);

    /// <summary>
    /// Encode the given data. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    string EncodeB64(byte[] data, out MteStatus status);

    /// <summary>
    /// Encode the given string. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    byte[] Encode(string data, out MteStatus status);

    /// <summary>
    /// Encode the given string. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    string EncodeB64(string data, out MteStatus status);

    /// <summary>
    /// Encode the given data of the given length at the given offset to the
    /// given buffer at the given offset. Returns the status. Sets encOff to the
    /// offset of the encoded version. Sets encBytes to the encoded length in
    /// bytes. The encoded buffer must have sufficient length remaining after
    /// the offset. Use GetBuffBytes() to determine the buffer requirement.
    /// </summary>
    MteStatus Encode(byte[] data, int dataOff, int dataBytes,
                     byte[] encoded, ref int encOff, out int encBytes);

    /// <summary>
    /// Encode the given data of the given length at the given offset to the
    /// given buffer at the given offset. Returns the status. Sets encOff to the
    /// offset of the encoded version. Sets encBytes to the encoded length in
    /// bytes. The encoded buffer must have sufficient length remaining after
    /// the offset. Use GetBuffBytes64() to determine the buffer requirement.
    /// </summary>
    MteStatus EncodeB64(byte[] data, int dataOff, int dataBytes,
                        byte[] encoded, ref int encOff, out int encBytes);
  }
}
#pragma warning restore 1591

