// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

using System;

namespace Eclypses.MTE {
  /// <summary>
  /// Interface MteDec
  ///
  /// This is the MTE decoder.
  /// </summary>
  public interface IMteDec : IMteCore {
    /// <summary>
    /// Returns the decode buffer size in bytes given the encoded length in
    /// bytes.
    /// </summary>
    int GetBuffBytes(int encodedBytes);

    /// <summary>
    /// Returns the decode buffer size in bytes given the encoded length in
    /// bytes.
    /// </summary>
    int GetBuffBytesB64(int encodedBytes);

    /// <summary>
    /// Decode the given encoded version. Returns the decoded data and sets
    /// status to the status.
    /// </summary>
    byte[] Decode(byte[] encoded, out MteStatus status);

    /// <summary>
    /// Decode the given encoded version. Returns the decoded data and sets
    /// status to the status.
    /// </summary>
    byte[] DecodeB64(string encoded, out MteStatus status);

    /// <summary>
    /// Decode the given message to a string. Returns the decoded string and
    /// sets status to the MTE status.
    /// </summary>
    string DecodeStr(byte[] encoded, out MteStatus status);

    /// <summary>
    /// Decode the given message to a string. Returns the decoded string and
    /// sets status to the MTE status.
    /// </summary>
    string DecodeStrB64(string encoded, out MteStatus status);

    /// <summary>
    /// Decode the given encoded version of the given length at the given offset
    /// to the given buffer at the given offset. Returns the status. Sets decOff
    /// to the offset of the decoded version. Sets decBytes to the decoded
    /// length in bytes. The decoded buffer must have sufficient length
    /// remaining after the offset. Use GetBuffBytes() to determine the buffer
    /// requirement.
    /// </summary>
    MteStatus Decode(byte[] encoded, int encOff, int encBytes,
                     byte[] decoded, ref int decOff, out int decBytes);

    /// <summary>
    /// Decode the given encoded version of the given length at the given offset
    /// to the given buffer at the given offset. Returns the status. Sets decOff
    /// to the offset of the decoded version. Sets decBytes to the decoded
    /// length in bytes. The decoded buffer must have sufficient length
    /// remaining after the offset. Use GetBuffBytes64() to determine the buffer
    /// requirement.
    /// </summary>
    MteStatus DecodeB64(byte[] encoded, int encOff, int encBytes,
                        byte[] decoded, ref int decOff, out int decBytes);

    /// <summary>
    /// Returns the timestamp set during encoding or 0 if there is no
    /// timestamp.
    /// </summary>
    UInt64 GetEncTs();

    /// <summary>
    /// Returns the timestamp set during decoding or 0 if there is no
    /// timestamp.
    /// </summary>
    UInt64 GetDecTs();

    /// <summary>
    /// Returns the number of messages that were skipped to get in sync
    /// during the decode or 0 if there is no sequencing.
    /// </summary>
    UInt32 GetMsgSkipped();
  }
}
#pragma warning restore 1591

