// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

using System;

namespace Eclypses.MTE {
  /// <summary>
  /// Interface MteCore
  ///
  /// This defines the interface common to all encoders and decoders.
  /// </summary>
  public interface IMteCore : IMteBase {
    /// <summary>
    /// Initialize the decoder with the personalization string. The entropy and
    /// nonce callbacks will be called to get the rest of the seeding material.
    /// Returns the status.
    /// </summary>
    MteStatus Instantiate(byte[] ps);

    /// <summary>
    /// Initialize the decoder with the personalization string. The entropy and
    /// nonce callbacks will be called to get the rest of the seeding material.
    /// Returns the status.
    /// </summary>
    MteStatus Instantiate(string ps);

    /// <summary>
    /// Returns the reseed counter.
    /// </summary>
    UInt64 GetReseedCounter();

    /// <summary>
    /// Returns the saved state. On error, null is returned.
    /// </summary>
    byte[] SaveState();

    /// <summary>
    /// Returns the Base64-encoded saved state. On error, null is returned.
    /// </summary>
    string SaveStateB64();

    /// <summary>
    /// Restore a saved state, which must be the same length as was returned
    /// from the SaveState() call. Returns the status.
    /// </summary>
    MteStatus RestoreState(byte[] saved);

    /// <summary>
    /// Restore a saved state, which must be the same length as was returned
    /// from the SaveStateB64() call. Returns the status.
    /// </summary>
    MteStatus RestoreStateB64(string saved);

    /// <summary>
    /// Uninstantiate the encoder/decoder. It is no longer usable after this
    /// call. Returns the status.
    /// </summary>
    MteStatus Uninstantiate();
  }
}
#pragma warning restore 1591

