// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

namespace Eclypses.MTE {
  /// <summary>
  /// Interface MteMkeDec
  ///
  /// This is the MTE Managed-Key Encryption decoder.
  /// </summary>
  public interface IMteMkeDec : IMteDec {
    /// <summary>
    /// Start a chunk-based decryption session. Returns the status.
    /// </summary>
    MteStatus StartDecrypt();

    /// <summary>
    /// Decrypt a chunk of data in a chunk-based decryption session. Returns the
    /// decrypted data. Returns null on error.
    /// </summary>
    byte[] DecryptChunk(byte[] encrypted);

    /// <summary>
    /// Decrypt a chunk of data at the given offset of the given length in a
    /// chunk-based decryption session. Some decrypted data is written to the
    /// decrypted buffer starting at decOff. The amount decrypted is returned.
    /// Returns -1 on error.
    /// </summary>
    int DecryptChunk(byte[] encrypted, int encOff, int encBytes,
                     byte[] decrypted, int decOff);

    /// <summary>
    /// Finish a chunk-based decryption session. Returns the final part of the
    /// result and sets status to the status.
    /// </summary>
    byte[] FinishDecrypt(out MteStatus status);

    /// <summary>
    /// Finish a chunk-based decryption session. Writes the final part of the
    /// result to the decrypted buffer starting at off. Sets bytes to the length
    /// of the result in bytes. Returns the status. The decrypted buffer must be
    /// large enough to hold at least the chosen cipher's block size in the mode
    /// of operation.
    /// </summary>
    MteStatus FinishDecrypt(byte[] decrypted, int off, out int bytes);
  }
}
#pragma warning restore 1591

