// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

using Eclypses.MTE.Interop;
using System;

namespace Eclypses.MTE {
  /// <summary>
  /// Interface IMteBase
  ///
  /// This is the base for encoders and decoders.
  /// </summary>
  public interface IMteBase {
    /// <summary>
    /// Returns the interop in use.
    /// </summary>
    MteInterop GetInterop();

    /// <summary>
    /// Returns the MTE version number as a string.
    /// </summary>
    string GetVersion();

    /// <summary>
    /// Returns the MTE major version number.
    /// </summary>
    int GetVersionMajor();

    /// <summary>
    /// Returns the MTE minor version number.
    /// </summary>
    int GetVersionMinor();

    /// <summary>
    /// Returns the MTE patch version number.
    /// </summary>
    int GetVersionPatch();

    /// <summary>
    /// Initialize with the company name and license code. Returns true if
    /// successful or false if not. If true is returned, MTE functions are
    /// usable; otherwise functions that return a status will return an error
    /// status.
    /// </summary>
    bool InitLicense(string company, string license);

    /// <summary>
    /// Returns the count of status codes.
    /// </summary>
    int GetStatusCount();

    /// <summary>
    /// Returns the enumeration name for the given status.
    /// </summary>
    string GetStatusName(MteStatus status);

    /// <summary>
    /// Returns the description for the given status.
    /// </summary>
    string GetStatusDescription(MteStatus status);

    /// <summary>
    /// Returns the status code for the given enumeration name.
    /// </summary>
    MteStatus GetStatusCode(string name);

    /// <summary>
    /// Returns true if the given status is an error, false if it is success or
    /// a warning.
    /// </summary>
    bool StatusIsError(MteStatus status);

    /// <summary>
    /// Returns true if runtime options are available or false if not.
    /// </summary>
    bool HasRuntimeOpts();

    /// <summary>
    /// Returns the default DRBG. If runtime options are not available, this
    /// is the only option available; otherwise it is a suitable default.
    /// </summary>
    MteDrbgs GetDefaultDrbg();

    /// <summary>
    /// Returns the default token size. If runtime options are not available,
    /// this is the only option available; otherwise it is a suitable default.
    /// </summary>
    int GetDefaultTokBytes();

    /// <summary>
    /// Returns the default verifiers. If runtime options are not available,
    /// this is the only option available; otherwise it is a suitable default.
    /// </summary>
    MteVerifiers GetDefaultVerifiers();

    /// <summary>
    /// Returns the default cipher. If runtime options are not available, this
    /// is the only option available; otherwise it is a suitable default.
    /// </summary>
    MteCiphers GetDefaultCipher();

    /// <summary>
    /// Returns the default hash. If runtime options are not available, this
    /// is the only option available; otherwise it is a suitable default.
    /// </summary>
    MteHashes GetDefaultHash();

    /// <summary>
    /// Returns the count of DRBG algorithms.
    /// </summary>
    int GetDrbgsCount();

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    string GetDrbgsName(MteDrbgs algo);

    /// <summary>
    /// Returns the algorithm for the given enumeration name.
    /// </summary>
    MteDrbgs GetDrbgsAlgo(string name);

    /// <summary>
    /// Returns the security strength for the given algorithm.
    /// </summary>
    int GetDrbgsSecStrengthBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the minimum personalization string size for the given algorithm.
    /// </summary>
    int GetDrbgsPersonalMinBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the maximum personalization string size for the given algorithm.
    /// </summary>
    UInt64 GetDrbgsPersonalMaxBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the minimum entropy size for the given algorithm.
    /// </summary>
    int GetDrbgsEntropyMinBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the maximum entropy size for the given algorithm.
    /// </summary>
    UInt64 GetDrbgsEntropyMaxBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the minimum nonce size for the given algorithm.
    /// </summary>
    int GetDrbgsNonceMinBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the maximum nonce size for the given algorithm.
    /// </summary>
    int GetDrbgsNonceMaxBytes(MteDrbgs algo);

    /// <summary>
    /// Returns the reseed interval for the given algorithm.
    /// </summary>
    UInt64 GetDrbgsReseedInterval(MteDrbgs algo);

    /// <summary>
    /// Set the increment DRBG to return an error during instantiation and
    /// uninstantiation (if true) or not (if false). This is useful for testing
    /// error handling. The flag is false until set with this.
    /// </summary>
    void SetIncrInstError(bool flag);

    /// <summary>
    /// Set the increment DRBG to produce an error after the given number of
    /// values have been generated (if flag is true) or turn off errors (if flag
    /// is false) other than the reseed error, which is always produced when the
    /// seed interval is reached. The flag is false until set with this.
    /// </summary>
    void SetIncrGenError(bool flag, int after);

    /// <summary>
    /// Returns the count of verifier algorithms.
    /// </summary>
    int GetVerifiersCount();

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    string GetVerifiersName(MteVerifiers algo);

    /// <summary>
    /// Returns the algorithm for the given enumeration name.
    /// </summary>
    MteVerifiers GetVerifiersAlgo(string name);

    /// <summary>
    /// Returns the count of cipher algorithms.
    /// </summary>
    int GetCiphersCount();

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    string GetCiphersName(MteCiphers algo);

    /// <summary>
    /// Returns the algorithm for the given name.
    /// </summary>
    MteCiphers GetCiphersAlgo(string name);

    /// <summary>
    /// Returns the block size for the given algorithm.
    /// </summary>
    int GetCiphersBlockBytes(MteCiphers algo);

    /// <summary>
    /// Returns the count of hash algorithms.
    /// </summary>
    int GetHashesCount();

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    string GetHashesName(MteHashes algo);

    /// <summary>
    /// Returns the algorithm for the given name.
    /// </summary>
    MteHashes GetHashesAlgo(string name);

    /// <summary>
    /// Return the DRBG option in use.
    /// </summary>
    MteDrbgs GetDrbg();

    /// <summary>
    /// Return the token size option in use.
    /// </summary>
    int GetTokBytes();

    /// <summary>
    /// Return the verifiers option in use.
    /// </summary>
    MteVerifiers GetVerifiers();

    /// <summary>
    /// Return the cipher option in use.
    /// </summary>
    MteCiphers GetCipher();

    /// <summary>
    /// Return the hash option in use.
    /// </summary>
    MteHashes GetHash();

    /// <summary>
    /// Set the entropy callback. If not null, it is called to get entropy. If
    /// null, the entropy set with SetEntropy() is used.
    /// </summary>
    void SetEntropyCallback(MteEntropyCallback cb);

    /// <summary>
    /// Set the entropy input value. This must be done before calling an
    /// instantiation method that will trigger the entropy callback.
    ///
    /// The entropy is zeroized when used by an instantiation call.
    ///
    /// If the entropy callback is null, entropyInput is used as the entropy.
    /// </summary>
    void SetEntropy(byte[] entropyInput);

    /// <summary>
    /// Set the nonce callback. If not null, it is called to get the nonce. If
    /// null, the nonce set with SetNonce() is used.
    /// </summary>
    void SetNonceCallback(MteNonceCallback cb);

    /// <summary>
    /// Set the nonce. This must be done before calling an instantiation method
    /// that will trigger the entropy callback.
    ///
    /// If the nonce callback is null, nonce is used as the nonce.
    /// </summary>
    void SetNonce(byte[] nonce);

    /// <summary>
    /// Calls SetNonce() with the nonce value as an array of byte in little
    /// endian.
    /// </summary>
    void SetNonce(UInt64 nonce);

    /// <summary>
    /// Set the timestamp callback. If not null, it is called to get the
    /// timestamp. If null, 0 is used.
    /// </summary>
    void SetTimestampCallback(MteTimestampCallback cb);
  }
}
#pragma warning restore 1591

