// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Determine if UTF-8 marshaling is supported.
#if !NETCOREAPP1_0 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETSTANDARD2_0 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45 && !NET451 && !NET452 && !NET46 && !NET461 && !NET462 && !NET47
#define UTF8_MARSHALING
#endif

// <auto-generated />
#pragma warning disable 1591

using Eclypses.MTE.Interop;
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Eclypses.MTE {
  /// <summary>
  /// Interface of an entropy input callback.
  /// </summary>
  public interface MteEntropyCallback {
    MteStatus EntropyCallback(int minEntropy,
                              int minLength,
                              UInt64 maxLength,
                              byte[] entropyInput,
                              ref UInt64 eiBytes,
                              out IntPtr entropyLong);
  }

  /// <summary>
  /// Interface of a nonce callback.
  /// </summary>
  public interface MteNonceCallback {
    void NonceCallback(int minLength,
                       int maxLength,
                       byte[] nonce,
                       out int nBytes);
  }

  /// <summary>
  /// Interface of a timestamp callback.
  /// </summary>
  public interface MteTimestampCallback {
    UInt64 TimestampCallback();
  }

  /// <summary>
  /// Class MteBase
  ///
  /// This is the base for encoders and decoders.
  ///
  /// To use, derive from this class to create a encoder or decoder. Derived
  /// implementations may want to override the callbacks for providing entropy,
  /// a nonce, and a timestamp, depending on their needs.
  /// </summary>
  public class MteBase : IMteBase {
    /// <summary>
    /// Constructor using a provided interop. This should be used only for
    /// access to the information accessor functions. Derived classes must call
    /// InitBase() from their constructor.
    ///
    /// If interop == null, the default interop is used.
    /// </summary>
    public MteBase(MteInterop interop = null) {
      // Create an interop if not provided.
      if (interop == null) {
        if (ourInterop == null) {
          ourInterop = new MteInterop();
        }
        myInterop = ourInterop;
      }
      else {
        // Use the provided interop.
        myInterop = interop;
      }

      // Initialize if necessary.
      if (!ourMteInitialized) {
        // Do global init.
        if (myInterop.mte_init(IntPtr.Zero, IntPtr.Zero) == 0) {
          throw new Exception("MteBase: MTE init error.");
        }
        ourMteInitialized = true;

        // Check version.
        if (GetVersionMajor() != MteVersion.ourVersionMajor ||
            GetVersionMinor() != MteVersion.ourVersionMinor ||
            GetVersionPatch() != MteVersion.ourVersionPatch) {
          throw new Exception("MteBase: MTE version mismatch.");
        }
      }
    }

    /// <summary>
    /// Destructor.
    /// </summary>
    ~MteBase() {
      // Free buffers.
      if (myEntropyHandle.IsAllocated) {
        myEntropyHandle.Free();
      }
    }

    /// <summary>
    /// Returns the interop in use.
    /// </summary>
    public MteInterop GetInterop() {
      return myInterop;
    }

    /// <summary>
    /// Returns the MTE version number as a string.
    /// </summary>
    public string GetVersion() {
      return MteInterop.GetCString(myInterop.mte_base_version());
    }

    /// <summary>
    /// Returns the MTE major version number.
    /// </summary>
    public int GetVersionMajor() {
      return (int)myInterop.mte_base_version_major();
    }

    /// <summary>
    /// Returns the MTE minor version number.
    /// </summary>
    public int GetVersionMinor() {
      return (int)myInterop.mte_base_version_minor();
    }

    /// <summary>
    /// Returns the MTE patch version number.
    /// </summary>
    public int GetVersionPatch() {
      return (int)myInterop.mte_base_version_patch();
    }

    /// <summary>
    /// Initialize with the company name and license code. Returns true if
    /// successful or false if not. If true is returned, MTE functions are
    /// usable; otherwise functions that return a status will return an error
    /// status.
    /// </summary>
    public bool InitLicense(string company, string license) {
#if UTF8_MARSHALING
      return myInterop.mte_license_init(company, license) != 0;
#else
      byte[] company8 = MteInterop.GetUtf8Unshared(company);
      byte[] license8 = myInterop.GetUtf8(license);
      return myInterop.mte_license_init(company8, license8) != 0;
#endif
    }

    /// <summary>
    /// Returns the count of status codes.
    /// </summary>
    public int GetStatusCount() {
      return (int)myInterop.mte_base_status_count();
    }

    /// <summary>
    /// Returns the enumeration name for the given status.
    /// </summary>
    public string GetStatusName(MteStatus status) {
      return MteInterop.GetCString(myInterop.mte_base_status_name(status));
    }

    /// <summary>
    /// Returns the description for the given status.
    /// </summary>
    public string GetStatusDescription(MteStatus status) {
      return MteInterop.GetCString(
        myInterop.mte_base_status_description(status));
    }

    /// <summary>
    /// Returns the status code for the given enumeration name.
    /// </summary>
    public MteStatus GetStatusCode(string name) {
#if UTF8_MARSHALING
      return myInterop.mte_base_status_code(name);
#else
      byte[] name8 = myInterop.GetUtf8(name);
      return myInterop.mte_base_status_code(name8);
#endif
    }

    /// <summary>
    /// Returns true if the given status is an error, false if it is success or
    /// a warning.
    /// </summary>
    public bool StatusIsError(MteStatus status) {
      return myInterop.mte_base_status_is_error(status) != 0;
    }

    /// <summary>
    /// Returns true if runtime options are available or false if not.
    /// </summary>
    public bool HasRuntimeOpts() {
      return myInterop.mte_base_has_runtime_opts() != 0;
    }

    /// <summary>
    /// Returns the default DRBG. If runtime options are not available, this
    /// is the only option available; otherwise it is a suitable default.
    /// </summary>
    public MteDrbgs GetDefaultDrbg() {
      return myInterop.mte_base_default_drbg();
    }

    /// <summary>
    /// Returns the default token size. If runtime options are not available,
    /// this is the only option available; otherwise it is a suitable default.
    /// </summary>
    public int GetDefaultTokBytes() {
      return (int)myInterop.mte_base_default_tok_bytes();
    }

    /// <summary>
    /// Returns the default verifiers. If runtime options are not available,
    /// this is the only option available; otherwise it is a suitable default.
    /// </summary>
    public MteVerifiers GetDefaultVerifiers() {
      return myInterop.mte_base_default_verifiers();
    }

    /// <summary>
    /// Returns the default cipher. If runtime options are not available, this
    /// is the only option available; otherwise it is a suitable default.
    /// </summary>
    public MteCiphers GetDefaultCipher() {
      return myInterop.mte_base_default_cipher();
    }

    /// <summary>
    /// Returns the default hash. If runtime options are not available, this
    /// is the only option available; otherwise it is a suitable default.
    /// </summary>
    public MteHashes GetDefaultHash() {
      return myInterop.mte_base_default_hash();
    }

    /// <summary>
    /// Returns the count of DRBG algorithms.
    /// </summary>
    public int GetDrbgsCount() {
      return (int)myInterop.mte_base_drbgs_count();
    }

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    public string GetDrbgsName(MteDrbgs algo) {
      return MteInterop.GetCString(myInterop.mte_base_drbgs_name(algo));
    }

    /// <summary>
    /// Returns the algorithm for the given enumeration name.
    /// </summary>
    public MteDrbgs GetDrbgsAlgo(string name) {
#if UTF8_MARSHALING
      return myInterop.mte_base_drbgs_algo(name);
#else
      byte[] name8 = myInterop.GetUtf8(name);
      return myInterop.mte_base_drbgs_algo(name8);
#endif
    }

    /// <summary>
    /// Returns the security strength for the given algorithm.
    /// </summary>
    public int GetDrbgsSecStrengthBytes(MteDrbgs algo) {
      return (int)myInterop.mte_base_drbgs_sec_strength_bytes(algo);
    }

    /// <summary>
    /// Returns the minimum personalization string size for the given algorithm.
    /// </summary>
    public int GetDrbgsPersonalMinBytes(MteDrbgs algo) {
      return (int)myInterop.mte_base_drbgs_personal_min_bytes(algo);
    }

    /// <summary>
    /// Returns the maximum personalization string size for the given algorithm.
    /// </summary>
    public UInt64 GetDrbgsPersonalMaxBytes(MteDrbgs algo) {
      return myInterop.mte_base_drbgs_personal_max_bytes(algo);
    }

    /// <summary>
    /// Returns the minimum entropy size for the given algorithm.
    /// </summary>
    public int GetDrbgsEntropyMinBytes(MteDrbgs algo) {
      return (int)myInterop.mte_base_drbgs_entropy_min_bytes(algo);
    }

    /// <summary>
    /// Returns the maximum entropy size for the given algorithm.
    /// </summary>
    public UInt64 GetDrbgsEntropyMaxBytes(MteDrbgs algo) {
      return myInterop.mte_base_drbgs_entropy_max_bytes(algo);
    }

    /// <summary>
    /// Returns the minimum nonce size for the given algorithm.
    /// </summary>
    public int GetDrbgsNonceMinBytes(MteDrbgs algo) {
      return (int)myInterop.mte_base_drbgs_nonce_min_bytes(algo);
    }

    /// <summary>
    /// Returns the maximum nonce size for the given algorithm.
    /// </summary>
    public int GetDrbgsNonceMaxBytes(MteDrbgs algo) {
      return (int)myInterop.mte_base_drbgs_nonce_max_bytes(algo);
    }

    /// <summary>
    /// Returns the reseed interval for the given algorithm.
    /// </summary>
    public UInt64 GetDrbgsReseedInterval(MteDrbgs algo) {
      return myInterop.mte_base_drbgs_reseed_interval(algo);
    }

    /// <summary>
    /// Set the increment DRBG to return an error during instantiation and
    /// uninstantiation (if true) or not (if false). This is useful for testing
    /// error handling. The flag is false until set with this.
    /// </summary>
    public void SetIncrInstError(bool flag) {
      myInterop.mte_base_drbgs_incr_inst_error(flag ? 1 : 0);
    }

    /// <summary>
    /// Set the increment DRBG to produce an error after the given number of
    /// values have been generated (if flag is true) or turn off errors (if flag
    /// is false) other than the reseed error, which is always produced when the
    /// seed interval is reached. The flag is false until set with this.
    /// </summary>
    public void SetIncrGenError(bool flag, int after) {
      myInterop.mte_base_drbgs_incr_gen_error(flag ? 1 : 0, (UInt32)after);
    }

    /// <summary>
    /// Returns the count of verifier algorithms.
    /// </summary>
    public int GetVerifiersCount() {
      return (int)myInterop.mte_base_verifiers_count();
    }

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    public string GetVerifiersName(MteVerifiers algo) {
      return MteInterop.GetCString(myInterop.mte_base_verifiers_name(algo));
    }

    /// <summary>
    /// Returns the algorithm for the given enumeration name.
    /// </summary>
    public MteVerifiers GetVerifiersAlgo(string name) {
#if UTF8_MARSHALING
      return myInterop.mte_base_verifiers_algo(name);
#else
      byte[] name8 = myInterop.GetUtf8(name);
      return myInterop.mte_base_verifiers_algo(name8);
#endif
    }

    /// <summary>
    /// Returns the count of cipher algorithms.
    /// </summary>
    public int GetCiphersCount() {
      return (int)myInterop.mte_base_ciphers_count();
    }

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    public string GetCiphersName(MteCiphers algo) {
      return MteInterop.GetCString(myInterop.mte_base_ciphers_name(algo));
    }

    /// <summary>
    /// Returns the algorithm for the given name.
    /// </summary>
    public MteCiphers GetCiphersAlgo(string name) {
#if UTF8_MARSHALING
      return myInterop.mte_base_ciphers_algo(name);
#else
      byte[] name8 = myInterop.GetUtf8(name);
      return myInterop.mte_base_ciphers_algo(name8);
#endif
    }

    /// <summary>
    /// Returns the block size for the given algorithm.
    /// </summary>
    public int GetCiphersBlockBytes(MteCiphers algo) {
      return (int)myInterop.mte_base_ciphers_block_bytes(algo);
    }

    /// <summary>
    /// Returns the count of hash algorithms.
    /// </summary>
    public int GetHashesCount() {
      return (int)myInterop.mte_base_hashes_count();
    }

    /// <summary>
    /// Returns the enumeration name for the given algorithm.
    /// </summary>
    public string GetHashesName(MteHashes algo) {
      return MteInterop.GetCString(myInterop.mte_base_hashes_name(algo));
    }

    /// <summary>
    /// Returns the algorithm for the given name.
    /// </summary>
    public MteHashes GetHashesAlgo(string name) {
#if UTF8_MARSHALING
      return myInterop.mte_base_hashes_algo(name);
#else
      byte[] name8 = myInterop.GetUtf8(name);
      return myInterop.mte_base_hashes_algo(name8);
#endif
    }

    /// <summary>
    /// Return the DRBG option in use.
    /// </summary>
    public MteDrbgs GetDrbg() { return myDrbg; }

    /// <summary>
    /// Return the token size option in use.
    /// </summary>
    public int GetTokBytes() { return myTokBytes; }

    /// <summary>
    /// Return the verifiers option in use.
    /// </summary>
    public MteVerifiers GetVerifiers() { return myVerifiers; }

    /// <summary>
    /// Return the cipher option in use.
    /// </summary>
    public MteCiphers GetCipher() { return myCipher; }

    /// <summary>
    /// Return the hash option in use.
    /// </summary>
    public MteHashes GetHash() { return myHash; }

    /// <summary>
    /// Set the entropy callback. If not null, it is called to get entropy. If
    /// null, the entropy set with SetEntropy() is used.
    /// </summary>
    public void SetEntropyCallback(MteEntropyCallback cb) {
      myEntropyCb = cb;
    }

    /// <summary>
    /// Set the entropy input value. This must be done before calling an
    /// instantiation method that will trigger the entropy callback.
    ///
    /// The entropy is zeroized when used by an instantiation call.
    ///
    /// If the entropy callback is null, entropyInput is used as the entropy.
    /// </summary>
    public void SetEntropy(byte[] entropyInput) {
      // Free a previously-allocated GC handle.
      if (myEntropyHandle.IsAllocated) {
        myEntropyHandle.Free();
      }

      myEntropyInput = entropyInput;
    }

    /// <summary>
    /// Set the nonce callback. If not null, it is called to get the nonce. If
    /// null, the nonce set with SetNonce() is used.
    /// </summary>
    public void SetNonceCallback(MteNonceCallback cb) {
      myNonceCb = cb;
    }

    /// <summary>
    /// Set the nonce. This must be done before calling an instantiation method
    /// that will trigger the entropy callback.
    ///
    /// If the nonce callback is null, nonce is used as the nonce.
    /// </summary>
    public void SetNonce(byte[] nonce) {
      myNonce = nonce;
    }

    /// <summary>
    /// Calls SetNonce() with the nonce value as an array of byte in little
    /// endian.
    /// </summary>
    public void SetNonce(UInt64 nonce) {
      // Allocate a buffer if necessary.
      if (myNonce == null || myNonce.Length != myNonceIntBytes) {
        myNonce = new byte[myNonceIntBytes];
      }

      // Copy as little endian.
      for (int i = 0; i < sizeof(UInt64) && i < myNonceIntBytes; ++i) {
        myNonce[i] = (byte)(nonce >> (i * 8));
      }
      for (int i = sizeof(UInt64); i < myNonceIntBytes; ++i) {
        myNonce[i] = 0;
      }
    }

    /// <summary>
    /// Set the timestamp callback. If not null, it is called to get the
    /// timestamp. If null, 0 is used.
    /// </summary>
    public void SetTimestampCallback(MteTimestampCallback cb) {
      myTimestampCb = cb;
    }

    /// <summary>
    /// Initialize.
    /// </summary>
    protected void InitBase(MteDrbgs drbg,
                            int tokBytes,
                            MteVerifiers verifiers,
                            MteCiphers cipher,
                            MteHashes hash) {
      // Set options.
      myDrbg = drbg;
      myTokBytes = tokBytes;
      myVerifiers = verifiers;
      myCipher = cipher;
      myHash = hash;

      // The ideal nonce length is the size of the nonce integer, but it
      // must be at least the minimum for the DRBG and no more than the
      // maximum for the DRBG.
      myNonceIntBytes = Math.Max(GetDrbgsNonceMinBytes(drbg),
                                 Math.Min(sizeof(UInt64),
                                          GetDrbgsNonceMaxBytes(drbg)));
    }

    /// <summary>
    /// Return a string from the byte buffer that contains a (possibly) null-
    /// terminated C string, assumed to be UTF-8.
    /// </summary>
    protected static string GetCString(byte[] buff) {
      return GetCString(buff, 0);
    }

    /// <summary>
    /// Return a string from the byte buffer that contains a (possibly) null-
    /// terminated C string, assumed to be UTF-8.
    /// </summary>
    protected static string GetCString(byte[] buff, int startOff) {
      // Find the null terminator.
      int endOff = Array.IndexOf<byte>(buff, 0, startOff);
      if (endOff < 0) {
        endOff = buff.Length;
      }

      // Convert to string.
      int bytes = endOff - startOff;
      return Encoding.UTF8.GetString(buff, startOff, bytes);
    }

    /// <summary>
    /// Internal entropy callback.
    /// </summary>
    protected MteStatus MteBaseEntropyCallback(IntPtr context,
                                               UInt32 minEntropy,
                                               UInt32 minLength,
                                               UInt64 maxLength,
                                               ref IntPtr entropyInput,
                                               ref UInt64 eiBytes) {
      IntPtr eiLong;
      UInt64 eib = eiBytes;
      byte[] ei = new byte[eiBytes];
      MteStatus status = EntropyCallback((int)minEntropy,
                                         (int)minLength,
                                         maxLength,
                                         ei,
                                         ref eiBytes,
                                         out eiLong);
      if (eiLong != IntPtr.Zero) {
        entropyInput = eiLong;
      }
      else if (eiBytes <= eib) {
        Marshal.Copy(ei, 0, entropyInput, (int)eiBytes);
        Array.Clear(ei, 0, ei.Length);
      }
      return status;
    }

    /// <summary>
    /// Internal nonce callback.
    /// </summary>
    protected void MteBaseNonceCallback(IntPtr context,
                                        UInt32 minLength,
                                        UInt32 maxLength,
                                        IntPtr nonce,
                                        out UInt32 nBytes) {
      int nb;
      byte[] n = new byte[maxLength];
      NonceCallback((int)minLength, (int)maxLength, n, out nb);
      Marshal.Copy(n, 0, nonce, nb);
      nBytes = (UInt32)nb;
    }

    /// <summary>
    /// Internal timestamp callback.
    /// </summary>
    protected UInt64 MteBaseTimestampCallback(IntPtr context) {
      return TimestampCallback();
    }

    /// <summary>
    /// The entropy callback.
    /// </summary>
    protected MteStatus EntropyCallback(int minEntropy,
                                        int minLength,
                                        UInt64 maxLength,
                                        byte[] entropyInput,
                                        ref UInt64 eiBytes,
                                        out IntPtr entropyLong) {
      // Call the callback if set.
      if (myEntropyCb != null) {
        return myEntropyCb.EntropyCallback(minEntropy,
                                           minLength,
                                           maxLength,
                                           entropyInput,
                                           ref eiBytes,
                                           out entropyLong);
      }

      // Check the length.
      int eiLen = myEntropyInput == null ? 0 : myEntropyInput.Length;
      if (eiLen < minLength || (UInt64)eiLen > maxLength) {
        entropyLong = IntPtr.Zero;
        return MteStatus.mte_status_drbg_catastrophic;
      }

      // Free a previously-allocated GC handle.
      if (myEntropyHandle.IsAllocated) {
        myEntropyHandle.Free();
      }

      // Create a GC handle to the buffer so it doesn't move.
      myEntropyHandle = GCHandle.Alloc(myEntropyInput, GCHandleType.Pinned);
      entropyLong = myEntropyHandle.AddrOfPinnedObject();

      // Success.
      eiBytes = (UInt64)eiLen;
      return MteStatus.mte_status_success;
    }

    /// <summary>
    /// The nonce callback.
    /// </summary>
    protected void NonceCallback(int minLength,
                                 int maxLength,
                                 byte[] nonce,
                                 out int nBytes) {
      // Call the callback if set.
      if (myNonceCb != null) {
        myNonceCb.NonceCallback(minLength, maxLength, nonce, out nBytes);
        return;
      }

      // Copy to the provided buffer.
      nBytes = myNonce.Length;
      Array.Copy(myNonce, nonce, myNonce.Length);
    }

    /// <summary>
    /// The timestamp callback.
    /// </summary>
    protected UInt64 TimestampCallback() {
      // Call the callback if set.
      if (myTimestampCb != null) {
        return myTimestampCb.TimestampCallback();
      }

      // Default to 0 otherwise.
      return 0;
    }

    /// <summary>
    /// Interop.
    /// </summary>
    protected MteInterop myInterop;

    /// <summary>
    /// Options.
    /// </summary>
    private MteDrbgs myDrbg;
    private int myTokBytes;
    private MteVerifiers myVerifiers;
    private MteCiphers myCipher;
    private MteHashes myHash;

    /// <summary>
    /// Callbacks.
    /// </summary>
    private MteEntropyCallback myEntropyCb = null;
    private MteNonceCallback myNonceCb = null;
    private MteTimestampCallback myTimestampCb = null;

    /// <summary>
    /// Instantiation inputs.
    /// </summary>
    private byte[] myEntropyInput;
    private byte[] myNonce;

    /// <summary>
    /// Nonce length when set as an integer.
    /// </summary>
    private int myNonceIntBytes;

    /// <summary>
    /// GC handle for pinning long entropy.
    /// </summary>
    private GCHandle myEntropyHandle;

    /// <summary>
    /// Default interop.
    /// </summary>
    static private MteInterop ourInterop = null;

    /// <summary>
    /// True if MTE is initialized, false if not.
    /// </summary>
    static private bool ourMteInitialized = false;
  }
}
#pragma warning restore 1591

