// Copyright (c) Eclypses, Inc.
// 
// All rights reserved.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// WARNING: This file is automatically generated. Do not edit.

// <auto-generated />
#pragma warning disable 1591
namespace Eclypses.MTE
{

  // Cipher algorithms.
  public enum MteCiphers
  {
    // None. An external cipher must be provided instead.
    mte_ciphers_none,

    // AES-128-CBC.
    mte_ciphers_aes128_cbc,

    // AES-128-CTR.
    mte_ciphers_aes128_ctr,

    // AES-128-ECB.
    mte_ciphers_aes128_ecb,

    // AES-192-CBC.
    mte_ciphers_aes192_cbc,

    // AES-192-CTR.
    mte_ciphers_aes192_ctr,

    // AES-192-ECB.
    mte_ciphers_aes192_ecb,

    // AES-256-CBC.
    mte_ciphers_aes256_cbc,

    // AES-256-CTR.
    mte_ciphers_aes256_ctr,

    // AES-256-ECB.
    mte_ciphers_aes256_ecb
  } 

}
#pragma warning restore 1591

