// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Determine if UTF-8 marshaling is supported.
#if !NETCOREAPP1_0 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETSTANDARD2_0 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45 && !NET451 && !NET452 && !NET46 && !NET461 && !NET462 && !NET47
#define UTF8_MARSHALING
#endif

// <auto-generated />
#pragma warning disable 1591

using System;
using System.Runtime.InteropServices;

namespace Eclypses.MTE.Interop {
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_VERSION();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_VERSION_MAJOR();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_VERSION_MINOR();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_VERSION_PATCH();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate Int32 MTE_INIT(IntPtr cb, IntPtr context);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate int MTE_LICENSE_INIT(
    [MarshalAs(UnmanagedType.LPUTF8Str)] string company,
    [MarshalAs(UnmanagedType.LPUTF8Str)] string license);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate int MTE_LICENSE_INIT(byte[] company, byte[] license);
#endif

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_STATUS_COUNT();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_STATUS_NAME(MteStatus status);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_STATUS_DESCRIPTION(MteStatus status);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_BASE_STATUS_CODE(
    [MarshalAs(UnmanagedType.LPUTF8Str)] string name);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_BASE_STATUS_CODE(byte[] name);
#endif

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate int MTE_BASE_STATUS_IS_ERROR(MteStatus status);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate int MTE_BASE_HAS_RUNTIME_OPTS();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteDrbgs MTE_BASE_DEFAULT_DRBG();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DEFAULT_TOK_BYTES();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteVerifiers MTE_BASE_DEFAULT_VERIFIERS();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteCiphers MTE_BASE_DEFAULT_CIPHER();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteHashes MTE_BASE_DEFAULT_HASH();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DRBGS_COUNT();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_DRBGS_NAME(MteDrbgs algo);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteDrbgs MTE_BASE_DRBGS_ALGO(
    [MarshalAs(UnmanagedType.LPUTF8Str)] string name);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteDrbgs MTE_BASE_DRBGS_ALGO(byte[] name);
#endif

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DRBGS_SEC_STRENGTH_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DRBGS_PERSONAL_MIN_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt64 MTE_BASE_DRBGS_PERSONAL_MAX_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DRBGS_ENTROPY_MIN_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt64 MTE_BASE_DRBGS_ENTROPY_MAX_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DRBGS_NONCE_MIN_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_DRBGS_NONCE_MAX_BYTES(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt64 MTE_BASE_DRBGS_RESEED_INTERVAL(MteDrbgs algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_BASE_DRBGS_INCR_INST_ERROR(int flag);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_BASE_DRBGS_INCR_GEN_ERROR(int flag, UInt32 after);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_VERIFIERS_COUNT();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_VERIFIERS_NAME(MteVerifiers algo);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteVerifiers MTE_BASE_VERIFIERS_ALGO(
    [MarshalAs(UnmanagedType.LPUTF8Str)] string name);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteVerifiers MTE_BASE_VERIFIERS_ALGO(byte[] name);
#endif

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_CIPHERS_COUNT();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_CIPHERS_NAME(MteCiphers algo);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteCiphers MTE_BASE_CIPHERS_ALGO(
    [MarshalAs(UnmanagedType.LPUTF8Str)] string name);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteCiphers MTE_BASE_CIPHERS_ALGO(byte[] name);
#endif

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_CIPHERS_BLOCK_BYTES(MteCiphers algo);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_BASE_HASHES_COUNT();

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate IntPtr MTE_BASE_HASHES_NAME(MteHashes algo);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteHashes MTE_BASE_HASHES_ALGO(
    [MarshalAs(UnmanagedType.LPUTF8Str)] string name);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteHashes MTE_BASE_HASHES_ALGO(byte[] name);
#endif

  // Method signatures for the internal callbacks.
  public delegate MteStatus ENTROPY_CALLBACK(IntPtr context,
                                             UInt32 minEntropy,
                                             UInt32 minLength,
                                             UInt64 maxLength,
                                             ref IntPtr entropyInput,
                                             ref UInt64 eiBytes);
  public delegate void NONCE_CALLBACK(IntPtr context,
                                      UInt32 minLength,
                                      UInt32 maxLength,
                                      IntPtr nonce,
                                      out UInt32 nBytes);
  public delegate UInt64 TIMESTAMP_CALLBACK(IntPtr context);
}
#pragma warning restore 1591

