// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Determine if UTF-8 marshaling is supported.
#if !NETCOREAPP1_0 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETSTANDARD2_0 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45 && !NET451 && !NET452 && !NET46 && !NET461 && !NET462 && !NET47
#define UTF8_MARSHALING
#endif

// <auto-generated />
#pragma warning disable 1591

using System;
using System.Runtime.InteropServices;

namespace Eclypses.MTE.Interop {
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_ENC_STATE_BYTES(MteDrbgs drbg,
                                             UInt32 tokBytes,
                                             MteVerifiers verifiers);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_STATE_INIT(IntPtr state,
                                               MteDrbgs drbg,
                                               UInt32 tokBytes,
                                               MteVerifiers verifiers);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_INSTANTIATE(IntPtr state,
                                                ENTROPY_CALLBACK eiCb,
                                                IntPtr eiCbContext,
                                                NONCE_CALLBACK nCb,
                                                IntPtr nCbContext,
                                                byte[] ps, UInt32 psBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt64 MTE_ENC_RESEED_COUNTER(IntPtr state);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_ENC_SAVE_BYTES(IntPtr state);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_ENC_SAVE_BYTES_B64(IntPtr state);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_STATE_SAVE(IntPtr state, IntPtr saved);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_STATE_SAVE_B64(IntPtr state, IntPtr saved);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_STATE_RESTORE(IntPtr state, byte[] saved);

#if UTF8_MARSHALING
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_STATE_RESTORE_B64(IntPtr state,
                             [MarshalAs(UnmanagedType.LPUTF8Str)] string saved);
#else
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_STATE_RESTORE_B64(IntPtr state,
                                                      byte[] saved);
#endif

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_ENC_BUFF_BYTES(IntPtr state, UInt32 dataBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate UInt32 MTE_ENC_BUFF_BYTES_B64(IntPtr state, UInt32 dataBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_ENCODE_A(IntPtr state,
                                             TIMESTAMP_CALLBACK tCb,
                                             IntPtr tCbContext,
                                             byte[] data, UInt32 dataBytes,
                                             IntPtr encoded,
                                             out UInt32 encodedOff,
                                             out UInt32 encodedBytes);
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_ENCODE_P(IntPtr state,
                                             TIMESTAMP_CALLBACK tCb,
                                             IntPtr tCbContext,
                                             IntPtr data, UInt32 dataBytes,
                                             IntPtr encoded,
                                             out UInt32 encodedOff,
                                             out UInt32 encodedBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_ENCODE_B64_A(IntPtr state,
                                                 TIMESTAMP_CALLBACK tCb,
                                                 IntPtr tCbContext,
                                                 byte[] data, UInt32 dataBytes,
                                                 IntPtr encoded,
                                                 out UInt32 encodedOff,
                                                 out UInt32 encodedBytes);
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_ENCODE_B64_P(IntPtr state,
                                                 TIMESTAMP_CALLBACK tCb,
                                                 IntPtr tCbContext,
                                                 IntPtr data, UInt32 dataBytes,
                                                 IntPtr encoded,
                                                 out UInt32 encodedOff,
                                                 out UInt32 encodedBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate MteStatus MTE_ENC_UNINSTANTIATE(IntPtr state);
}
#pragma warning restore 1591

