// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

using System;
using System.Runtime.InteropServices;

namespace Eclypses.MTE.Interop {
  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_JAIL_N_CB_ANDROID_ARM32_D(byte[] seed,
                                                     UInt32 seedBytes,
                                                     UInt32 minLength,
                                                     UInt32 maxLength,
                                                     byte[] nonce,
                                                     out UInt32 nBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_JAIL_N_CB_ANDROID_ARM64_D(byte[] seed,
                                                     UInt32 seedBytes,
                                                     UInt32 minLength,
                                                     UInt32 maxLength,
                                                     byte[] nonce,
                                                     out UInt32 nBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_JAIL_N_CB_ANDROID_X86_S(byte[] seed,
                                                   UInt32 seedBytes,
                                                   UInt32 minLength,
                                                   UInt32 maxLength,
                                                   byte[] nonce,
                                                   out UInt32 nBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_JAIL_N_CB_ANDROID_X86_64_S(byte[] seed,
                                                      UInt32 seedBytes,
                                                      UInt32 minLength,
                                                      UInt32 maxLength,
                                                      byte[] nonce,
                                                      out UInt32 nBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_JAIL_N_CB_IOS_ARM64_D(byte[] seed,
                                                 UInt32 seedBytes,
                                                 UInt32 minLength,
                                                 UInt32 maxLength,
                                                 byte[] nonce,
                                                 out UInt32 nBytes);

  [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
  public delegate void MTE_JAIL_N_CB_IOS_X86_64_S(byte[] seed,
                                                  UInt32 seedBytes,
                                                  UInt32 minLength,
                                                  UInt32 maxLength,
                                                  byte[] nonce,
                                                  out UInt32 nBytes);
}
#pragma warning restore 1591

