// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Determine if UTF-8 marshaling is supported.
#if !NETCOREAPP1_0 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETSTANDARD2_0 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45 && !NET451 && !NET452 && !NET46 && !NET461 && !NET462 && !NET47
#define UTF8_MARSHALING
#endif

// <auto-generated />
#pragma warning disable 1591

using Eclypses.MTE.Interop;
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Eclypses.MTE {
  /// <summary>
  /// Class MteEnc
  ///
  /// This is the MTE encoder.
  ///
  /// To use, create an object of this type, call Instantiate(), call Encode()
  /// zero or more times to encode each piece of data, then optionally call
  /// Uninstantiate() to clear the random state.
  ///
  /// Alternatively, the state can be saved any time after Instantiate() and
  /// restored instead of Instantiate() to pick up at a known point.
  /// </summary>
  public class MteEnc : MteBase, IMteEnc {
    /// <summary>
    /// Constructor using default options. The default interop is used.
    /// </summary>
    public MteEnc() : this(null) { }

    /// <summary>
    /// Constructor using default options. The provided interop is used.
    /// </summary>
    public MteEnc(MteInterop interop) : base(interop) {
      Init(GetDefaultDrbg(), GetDefaultTokBytes(), GetDefaultVerifiers());
    }

    /// <summary>
    /// Constructor taking the DRBG, token size in bytes, and verifiers
    /// algorithm. The default interop is used.
    /// </summary>
    public MteEnc(MteDrbgs drbg,
                  int tokBytes,
                  MteVerifiers verifiers) : this(null,
                                                 drbg,
                                                 tokBytes,
                                                 verifiers) { }

    /// <summary>
    /// Constructor taking a provided interop, the DRBG, token size in bytes,
    /// and verifiers algorithm.
    /// </summary>
    public MteEnc(MteInterop interop,
                  MteDrbgs drbg,
                  int tokBytes,
                  MteVerifiers verifiers) : base(interop) {
      Init(drbg, tokBytes, verifiers);
    }

    /// <summary>
    /// Destructor. The Uninstantiate() method is called.
    /// </summary>
    ~MteEnc() {
      // Uninstantiate if constructed fully.
      if (myEncoder != IntPtr.Zero) {
        Uninstantiate();
      }

      // Deallocate the handles.
      if (myEncoderHandle.IsAllocated) {
        myEncoderHandle.Free();
      }
      if (myEncHandle.IsAllocated) {
        myEncHandle.Free();
      }
      if (mySaveHandle.IsAllocated) {
        mySaveHandle.Free();
      }
      if (mySaveHandle64.IsAllocated) {
        mySaveHandle64.Free();
      }
    }

    /// <summary>
    /// Instantiate the encoder with the personalization string. The entropy and
    /// nonce callbacks will be called to get the rest of the seeding material.
    /// Returns the status.
    /// </summary>
    public MteStatus Instantiate(byte[] ps) {
      return myInterop.mte_enc_instantiate(myEncoder,
                                           myEntropyCb, IntPtr.Zero,
                                           myNonceCb, IntPtr.Zero,
                                           ps, (UInt32)ps.Length);
    }

    /// <summary>
    /// Instantiate the encoder with the personalization string. The entropy and
    /// nonce callbacks will be called to get the rest of the seeding material.
    /// Returns the status.
    /// </summary>
    public MteStatus Instantiate(string ps) {
      return Instantiate(Encoding.UTF8.GetBytes(ps));
    }

    /// <summary>
    /// Returns the reseed counter.
    /// </summary>
    public UInt64 GetReseedCounter() {
      return myInterop.mte_enc_reseed_counter(myEncoder);
    }

    /// <summary>
    /// Returns the saved state.
    /// </summary>
    public byte[] SaveState() {
      MteStatus status = myInterop.mte_enc_state_save(myEncoder, mySave);
      return status == MteStatus.mte_status_success ? mySaveBuff : null;
    }

    /// <summary>
    /// Returns the Base64-encoded saved state.
    /// </summary>
    public string SaveStateB64() {
      MteStatus status =
        myInterop.mte_enc_state_save_b64(myEncoder, mySave64);
      return status == MteStatus.mte_status_success ? GetCString(mySaveBuff64) :
                                                      null;
    }

    /// <summary>
    /// Restore a saved state, which must be the same length as was returned
    /// from the SaveState() call. Returns the status.
    /// </summary>
    public MteStatus RestoreState(byte[] saved) {
      return myInterop.mte_enc_state_restore(myEncoder, saved);
    }

    /// <summary>
    /// Restore a saved state, which must be the same length as was returned
    /// from the SaveStateB64() call. Returns the status.
    /// </summary>
    public MteStatus RestoreStateB64(string saved) {
#if UTF8_MARSHALING
      return myInterop.mte_enc_state_restore_b64(myEncoder, saved);
#else
      byte[] saved8 = myInterop.GetUtf8(saved);
      return myInterop.mte_enc_state_restore_b64(myEncoder, saved8);
#endif
    }

    /// <summary>
    /// Returns the encode buffer size in bytes given the data length in bytes.
    /// </summary>
    public int GetBuffBytes(int dataBytes) {
      return (int)myInterop.mte_enc_buff_bytes(myEncoder, (UInt32)dataBytes);
    }

    /// <summary>
    /// Returns the encode buffer size in bytes given the data length in bytes.
    /// </summary>
    public int GetBuffBytesB64(int dataBytes) {
      return (int)myInterop.mte_enc_buff_bytes_b64(myEncoder,
                                                   (UInt32)dataBytes);
    }

    /// <summary>
    /// Encode the given data. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    public byte[] Encode(byte[] data, out MteStatus status) {
      // Get the encode buffer requirement and resize if necessary.
      int buffBytes = GetBuffBytes(data.Length);
      if (buffBytes > myEncBuff.Length) {
        if (myEncHandle.IsAllocated) {
          myEncHandle.Free();
        }
        myEncBuff = new byte[buffBytes];
        myEncHandle = GCHandle.Alloc(myEncBuff, GCHandleType.Pinned);
        myEnc = myEncHandle.AddrOfPinnedObject();
      }

      // Encode.
      UInt32 eOff;
      UInt32 eBytes;
      status = myInterop.mte_enc_encode_a(myEncoder,
                                          myTimestampCb, IntPtr.Zero,
                                          data, (UInt32)data.Length,
                                          myEnc, out eOff, out eBytes);
      if (status != MteStatus.mte_status_success) {
        return null;
      }

      // Return the encoded part.
      byte[] encoded = new byte[(int)eBytes];
      Array.Copy(myEncBuff, (int)eOff, encoded, 0, (int)eBytes);
      return encoded;
    }

    /// <summary>
    /// Encode the given data. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    public string EncodeB64(byte[] data, out MteStatus status) {
      // Get the encode buffer requirement and resize if necessary.
      int buffBytes = GetBuffBytesB64(data.Length);
      if (buffBytes > myEncBuff.Length) {
        if (myEncHandle.IsAllocated) {
          myEncHandle.Free();
        }
        myEncBuff = new byte[buffBytes];
        myEncHandle = GCHandle.Alloc(myEncBuff, GCHandleType.Pinned);
        myEnc = myEncHandle.AddrOfPinnedObject();
      }

      // Encode.
      UInt32 eOff;
      UInt32 eBytes;
      status = myInterop.mte_enc_encode_b64_a(myEncoder,
                                              myTimestampCb, IntPtr.Zero,
                                              data, (UInt32)data.Length,
                                              myEnc, out eOff, out eBytes);
      if (status != MteStatus.mte_status_success) {
        return null;
      }

      // Return the Base64-encoded message.
      return Encoding.UTF8.GetString(myEncBuff, (int)eOff, (int)eBytes);
    }

    /// <summary>
    /// Encode the given string. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    public byte[] Encode(string data, out MteStatus status) {
      return Encode(Encoding.UTF8.GetBytes(data), out status);
    }

    /// <summary>
    /// Encode the given string. Returns the encoded message and sets status to
    /// the status.
    /// </summary>
    public string EncodeB64(string data, out MteStatus status) {
      return EncodeB64(Encoding.UTF8.GetBytes(data), out status);
    }

    /// <summary>
    /// Encode the given data of the given length at the given offset to the
    /// given buffer at the given offset. Returns the status. Sets encOff to the
    /// offset of the encoded version. Sets encBytes to the encoded length in
    /// bytes. The encoded buffer must have sufficient length remaining after
    /// the offset. Use GetBuffBytes() to determine the buffer requirement.
    /// </summary>
    public MteStatus Encode(byte[] data, int dataOff, int dataBytes,
                            byte[] encoded, ref int encOff, out int encBytes) {
      // Pin the input array. Get a pointer to the offset.
      GCHandle dataHandle = GCHandle.Alloc(data, GCHandleType.Pinned);
      IntPtr dataPtr = Marshal.UnsafeAddrOfPinnedArrayElement(data, dataOff);

      // Pin the encoded array. Get a pointer to the offset.
      GCHandle encHandle = GCHandle.Alloc(encoded, GCHandleType.Pinned);
      IntPtr encPtr = Marshal.UnsafeAddrOfPinnedArrayElement(encoded, encOff);

      // Encode.
      UInt32 eOff;
      UInt32 eBytes;
      MteStatus status = myInterop.mte_enc_encode_p(myEncoder,
                                                    myTimestampCb, IntPtr.Zero,
                                                    dataPtr, (UInt32)dataBytes,
                                                    encPtr,
                                                    out eOff, out eBytes);
      encOff += (int)eOff;
      encBytes = (int)eBytes;

      // Unpin the arrays.
      dataHandle.Free();
      encHandle.Free();

      // Return status.
      return status;
    }

    /// <summary>
    /// Encode the given data of the given length at the given offset to the
    /// given buffer at the given offset. Returns the status. Sets encOff to the
    /// offset of the encoded version. Sets encBytes to the encoded length in
    /// bytes. The encoded buffer must have sufficient length remaining after
    /// the offset. Use GetBuffBytes64() to determine the buffer requirement.
    /// </summary>
    public MteStatus EncodeB64(byte[] data, int dataOff, int dataBytes,
                               byte[] encoded,
                               ref int encOff,
                               out int encBytes) {
      // Pin the input array. Get a pointer to the offset.
      GCHandle dataHandle = GCHandle.Alloc(data, GCHandleType.Pinned);
      IntPtr dataPtr = Marshal.UnsafeAddrOfPinnedArrayElement(data, dataOff);

      // Pin the encoded array. Get a pointer to the offset.
      GCHandle encHandle = GCHandle.Alloc(encoded, GCHandleType.Pinned);
      IntPtr encPtr = Marshal.UnsafeAddrOfPinnedArrayElement(encoded, encOff);

      // Encode.
      UInt32 eOff;
      UInt32 eBytes;
      MteStatus status = myInterop.mte_enc_encode_b64_p(myEncoder,
                                                        myTimestampCb,
                                                        IntPtr.Zero,
                                                        dataPtr,
                                                        (UInt32)dataBytes,
                                                        encPtr,
                                                        out eOff, out eBytes);
      encOff += (int)eOff;
      encBytes = (int)eBytes;

      // Unpin the arrays.
      dataHandle.Free();
      encHandle.Free();

      // Return status.
      return status;
    }

    /// <summary>
    /// Uninstantiate the encoder. It is no longer usable after this call.
    /// Returns the status.
    /// </summary>
    public MteStatus Uninstantiate() {
      return myInterop.mte_enc_uninstantiate(myEncoder);
    }

    /// <summary>
    /// Initialize.
    /// </summary>
    private void Init(MteDrbgs drbg,
                      int tokBytes,
                      MteVerifiers verifiers) {
      // Initialize the base.
      InitBase(drbg,
               tokBytes,
               verifiers,
               MteCiphers.mte_ciphers_none,
               MteHashes.mte_hashes_none);

      // Get the encoder size.
      int bytes = (int)myInterop.mte_enc_state_bytes(drbg,
                                                     (UInt32)tokBytes,
                                                     verifiers);
      if (bytes == 0) {
        throw new ArgumentOutOfRangeException("MteEnc.init: Invalid options.");
      }

      // Allocate the encoder and pin it to create a handle.
      myEncoderBuff = new byte[bytes];
      myEncoderHandle = GCHandle.Alloc(myEncoderBuff, GCHandleType.Pinned);
      myEncoder = myEncoderHandle.AddrOfPinnedObject();

      // Create the callbacks.
      myEntropyCb = new ENTROPY_CALLBACK(this.MteBaseEntropyCallback);
      myNonceCb = new NONCE_CALLBACK(this.MteBaseNonceCallback);
      myTimestampCb = new TIMESTAMP_CALLBACK(this.MteBaseTimestampCallback);

      // Initialize the encoder state.
      MteStatus status = myInterop.mte_enc_state_init(myEncoder,
                                                      drbg,
                                                      (UInt32)tokBytes,
                                                      verifiers);
      if (status != MteStatus.mte_status_success) {
        throw new ArgumentOutOfRangeException("MteEnc.init: Invalid options.");
      }

      // Allocate the save buffers.
      mySaveBuff = new byte[myInterop.mte_enc_save_bytes(myEncoder)];
      mySaveBuff64 = new byte[myInterop.mte_enc_save_bytes_b64(myEncoder)];
      mySaveHandle = GCHandle.Alloc(mySaveBuff, GCHandleType.Pinned);
      mySaveHandle64 = GCHandle.Alloc(mySaveBuff64, GCHandleType.Pinned);
      mySave = mySaveHandle.AddrOfPinnedObject();
      mySave64 = mySaveHandle64.AddrOfPinnedObject();
    }

    /// <summary>
    /// The encoder state.
    /// </summary>
    private IntPtr myEncoder;
    private byte[] myEncoderBuff;
    private GCHandle myEncoderHandle;

    /// <summary>
    /// Encoder buffer.
    /// </summary>
    private IntPtr myEnc;
    private byte[] myEncBuff = new byte[0];
    private GCHandle myEncHandle;

    /// <summary>
    /// State save buffer.
    /// </summary>
    private IntPtr mySave;
    private IntPtr mySave64;
    private byte[] mySaveBuff;
    private byte[] mySaveBuff64;
    private GCHandle mySaveHandle;
    private GCHandle mySaveHandle64;

    /// <summary>
    /// Callback delegates.
    /// </summary>
    private ENTROPY_CALLBACK myEntropyCb;
    private NONCE_CALLBACK myNonceCb;
    private TIMESTAMP_CALLBACK myTimestampCb;
  }
}
#pragma warning restore 1591

