// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

using System;

namespace Eclypses.MTE.Interop {
  /// <summary>
  /// Class MteInterop
  ///
  /// This class contains the interop functions for MTE.
  ///
  /// This partial class contains the interop functions for MteMkeDec.
  /// </summary>
  public partial class MteInterop {
    /// <summary>
    /// Interop functions.
    /// </summary>
    public MTE_MKE_DEC_STATE_BYTES mte_mke_dec_state_bytes;
    public MTE_MKE_DEC_STATE_INIT mte_mke_dec_state_init;
    public MTE_MKE_DEC_INSTANTIATE mte_mke_dec_instantiate;
    public MTE_MKE_DEC_RESEED_COUNTER mte_mke_dec_reseed_counter;
    public MTE_MKE_DEC_SAVE_BYTES mte_mke_dec_save_bytes;
    public MTE_MKE_DEC_SAVE_BYTES_B64 mte_mke_dec_save_bytes_b64;
    public MTE_MKE_DEC_STATE_SAVE mte_mke_dec_state_save;
    public MTE_MKE_DEC_STATE_SAVE_B64 mte_mke_dec_state_save_b64;
    public MTE_MKE_DEC_STATE_RESTORE mte_mke_dec_state_restore;
    public MTE_MKE_DEC_STATE_RESTORE_B64 mte_mke_dec_state_restore_b64;
    public MTE_MKE_DEC_BUFF_BYTES mte_mke_dec_buff_bytes;
    public MTE_MKE_DEC_BUFF_BYTES_B64 mte_mke_dec_buff_bytes_b64;
    public MTE_MKE_DEC_DECODE_A mte_mke_dec_decode_a;
    public MTE_MKE_DEC_DECODE_P mte_mke_dec_decode_p;
    public MTE_MKE_DEC_DECODE_B64_S mte_mke_dec_decode_b64_s;
    public MTE_MKE_DEC_DECODE_B64_P mte_mke_dec_decode_b64_p;
    public MTE_MKE_DEC_DECRYPT_STATE_BYTES mte_mke_dec_decrypt_state_bytes;
    public MTE_MKE_DEC_DECRYPT_START mte_mke_dec_decrypt_start;
    public MTE_MKE_DEC_DECRYPT_CHUNK_A mte_mke_dec_decrypt_chunk_a;
    public MTE_MKE_DEC_DECRYPT_CHUNK_P mte_mke_dec_decrypt_chunk_p;
    public MTE_MKE_DEC_DECRYPT_FINISH mte_mke_dec_decrypt_finish;
    public MTE_MKE_DEC_UNINSTANTIATE mte_mke_dec_uninstantiate;

    /// <summary>
    /// Load MteMkeDec parts.
    /// </summary>
    partial void LoadMkeDec(ILoader l) {
      myHasMke = l.GetSymbol("mte_wrap_mke_dec_state_bytes") != IntPtr.Zero;
      if (!myHasMke) {
        return;
      }
      BindDelegate(l, "mte_wrap_mke_dec_state_bytes",
                   out mte_mke_dec_state_bytes);
      BindDelegate(l, "mte_wrap_mke_dec_state_init",
                   out mte_mke_dec_state_init);
      BindDelegate(l, "mte_wrap_mke_dec_instantiate",
                   out mte_mke_dec_instantiate);
      BindDelegate(l, "mte_mke_dec_reseed_counter",
                   out mte_mke_dec_reseed_counter);
      BindDelegate(l, "mte_wrap_mke_dec_save_bytes",
                   out mte_mke_dec_save_bytes);
      BindDelegate(l, "mte_wrap_mke_dec_save_bytes_b64",
                   out mte_mke_dec_save_bytes_b64);
      BindDelegate(l, "mte_mke_dec_state_save", out mte_mke_dec_state_save);
      BindDelegate(l, "mte_wrap_mke_dec_state_save_b64",
                   out mte_mke_dec_state_save_b64);
      BindDelegate(l, "mte_mke_dec_state_restore",
                   out mte_mke_dec_state_restore);
      BindDelegate(l, "mte_wrap_mke_dec_state_restore_b64",
                   out mte_mke_dec_state_restore_b64);
      BindDelegate(l, "mte_wrap_mke_dec_buff_bytes",
                   out mte_mke_dec_buff_bytes);
      BindDelegate(l, "mte_wrap_mke_dec_buff_bytes_b64",
                   out mte_mke_dec_buff_bytes_b64);
      BindDelegate(l, "mte_wrap_mke_dec_decode", out mte_mke_dec_decode_a);
      BindDelegate(l, "mte_wrap_mke_dec_decode", out mte_mke_dec_decode_p);
      BindDelegate(l, "mte_wrap_mke_dec_decode_b64",
                   out mte_mke_dec_decode_b64_s);
      BindDelegate(l, "mte_wrap_mke_dec_decode_b64",
                   out mte_mke_dec_decode_b64_p);
      BindDelegate(l, "mte_wrap_mke_dec_decrypt_state_bytes",
                   out mte_mke_dec_decrypt_state_bytes);
      BindDelegate(l, "mte_mke_dec_decrypt_start",
                   out mte_mke_dec_decrypt_start);
      BindDelegate(l, "mte_wrap_mke_dec_decrypt_chunk",
                   out mte_mke_dec_decrypt_chunk_a);
      BindDelegate(l, "mte_wrap_mke_dec_decrypt_chunk",
                   out mte_mke_dec_decrypt_chunk_p);
      BindDelegate(l, "mte_wrap_mke_dec_decrypt_finish",
                   out mte_mke_dec_decrypt_finish);
      BindDelegate(l, "mte_mke_dec_uninstantiate",
                   out mte_mke_dec_uninstantiate);
    }
  }
}
#pragma warning restore 1591

