// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Determine if UTF-8 marshaling is supported.
#if !NETCOREAPP1_0 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETSTANDARD2_0 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45 && !NET451 && !NET452 && !NET46 && !NET461 && !NET462 && !NET47
#define UTF8_MARSHALING
#endif

// Determine if GetDelegateForFunctionPointer using the template syntax is
// supported.
#if !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45
#define GDFFP_TEMPLATE
#endif

// Determine if Environment.CurrentDirectory exists.
#if !NETCOREAPP1_0 && !NETCOREAPP1_1
#define E_CD
#endif

// <auto-generated />
#pragma warning disable 1591

using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

namespace Eclypses.MTE.Interop {
  /// <summary>
  /// Class MteInterop
  ///
  /// This class contains the interop functions for MTE.
  ///
  /// This partial class contains the interop functions for MteBase.
  /// </summary>
  public partial class MteInterop {
    /// <summary>
    /// Load the given library to provide the interop functions. The library
    /// name can be the base name (no prefix or extension) or filename without
    /// path, and must then be in the LD_LIBRARY_PATH/DYLD_LIBRARY_PATH/PATH
    /// (depending on OS), or can be a full path to a filename.
    /// </summary>
    public MteInterop(string libName = "mte") {
      // Determine the platform. Create the appropriate library loader for it.
      if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) {
        myLoader = new LinuxLoader(libName);
      }
      else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX)) {
        myLoader = new MacOsLoader(libName);
      }
      else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
        myLoader = new WindowsLoader(libName);
      }
      else {
        throw new InvalidOperationException("MteInterop: Unsupported OS.");
      }

      // Load parts.
      LoadBase(myLoader);
      LoadDec(myLoader);
      LoadEnc(myLoader);
      LoadFlenEnc(myLoader);
      LoadJail(myLoader);
      LoadMkeDec(myLoader);
      LoadMkeEnc(myLoader);
    }

    /// <summary>
    /// Returns true if the add-on is loaded or false if not.
    /// </summary>
    public bool HasFlen() {
      return myHasFlen;
    }

    /// <summary>
    /// Returns true if the add-on is loaded or false if not.
    /// </summary>
    public bool HasJail() {
      return myHasJail;
    }

    /// <summary>
    /// Returns true if the add-on is loaded or false if not.
    /// </summary>
    public bool HasMke() {
      return myHasMke;
    }

    /// <summary>
    /// Close/unload the library. All delegates are invalid after this call.
    /// Returns true if successful, false if not.
    /// </summary>
    public bool Close() {
      return myLoader.Close();
    }

#if !UTF8_MARSHALING
    /// <summary>
    /// Convert the given string to a UTF-8 byte array with a null terminator.
    /// It may have extra null bytes at the end, so the length of the returned
    /// byte array may not reflect the string's length. The byte array returned
    /// is shared across calls.
    /// </summary>
    internal byte[] GetUtf8(string str) {
      // Determine the length of the byte array necessary to represent the
      // string in UTF-8 with a null terminator. UTF-16 strings can no more than
      // double the number of code points when converted to UTF-8.
      int bytes = (str.Length * 2) + 1;
      if (myUtf8.Length < bytes) {
        myUtf8 = new byte[bytes];
      }

      // Convert to UTF-8. Ensure null termination.
      bytes = Encoding.UTF8.GetBytes(str, 0, str.Length, myUtf8, 0);
      myUtf8[bytes] = 0;
      return myUtf8;
    }

    /// <summary>
    /// Convert the given string to a UTF-8 byte array with a null terminator.
    /// It may have extra null bytes at the end, so the length of the returned
    /// byte array may not reflect the string's length.
    /// </summary>
    internal static byte[] GetUtf8Unshared(string str) {
      // Determine the length of the byte array necessary to represent the
      // string in UTF-8 with a null terminator. UTF-16 strings can no more than
      // double the number of code points when converted to UTF-8.
      int bytes = (str.Length * 2) + 1;
      byte[] utf8 = new byte[bytes];

      // Convert to UTF-8.
      Encoding.UTF8.GetBytes(str, 0, str.Length, utf8, 0);
      return utf8;
    }
#endif

    /// <summary>
    /// Return a string from the IntPtr that points at a null-terminated C
    /// string, assumed to be UTF-8. If ptr is null, null is returned.
    /// </summary>
    internal static string GetCString(IntPtr ptr) {
      // Check for null.
      if (ptr == IntPtr.Zero) {
        return null;
      }

      // Find the null terminator.
      int length = 0;
      while (Marshal.ReadByte(ptr, length) != 0) {
        ++length;
      }

      // Copy to a buffer. Convert to string.
      byte[] buffer = new byte[length];
      Marshal.Copy(ptr, buffer, 0, length);
      return Encoding.UTF8.GetString(buffer);
    }

    /// <summary>
    /// Interop functions.
    /// </summary>
    public MTE_BASE_VERSION mte_base_version;
    public MTE_BASE_VERSION_MAJOR mte_base_version_major;
    public MTE_BASE_VERSION_MINOR mte_base_version_minor;
    public MTE_BASE_VERSION_PATCH mte_base_version_patch;
    public MTE_INIT mte_init;
    public MTE_LICENSE_INIT mte_license_init;
    public MTE_BASE_STATUS_COUNT mte_base_status_count;
    public MTE_BASE_STATUS_NAME mte_base_status_name;
    public MTE_BASE_STATUS_DESCRIPTION mte_base_status_description;
    public MTE_BASE_STATUS_CODE mte_base_status_code;
    public MTE_BASE_STATUS_IS_ERROR mte_base_status_is_error;
    public MTE_BASE_HAS_RUNTIME_OPTS mte_base_has_runtime_opts;
    public MTE_BASE_DEFAULT_DRBG mte_base_default_drbg;
    public MTE_BASE_DEFAULT_TOK_BYTES mte_base_default_tok_bytes;
    public MTE_BASE_DEFAULT_VERIFIERS mte_base_default_verifiers;
    public MTE_BASE_DEFAULT_CIPHER mte_base_default_cipher;
    public MTE_BASE_DEFAULT_HASH mte_base_default_hash;
    public MTE_BASE_DRBGS_COUNT mte_base_drbgs_count;
    public MTE_BASE_DRBGS_NAME mte_base_drbgs_name;
    public MTE_BASE_DRBGS_ALGO mte_base_drbgs_algo;
    public MTE_BASE_DRBGS_SEC_STRENGTH_BYTES mte_base_drbgs_sec_strength_bytes;
    public MTE_BASE_DRBGS_PERSONAL_MIN_BYTES mte_base_drbgs_personal_min_bytes;
    public MTE_BASE_DRBGS_PERSONAL_MAX_BYTES mte_base_drbgs_personal_max_bytes;
    public MTE_BASE_DRBGS_ENTROPY_MIN_BYTES mte_base_drbgs_entropy_min_bytes;
    public MTE_BASE_DRBGS_ENTROPY_MAX_BYTES mte_base_drbgs_entropy_max_bytes;
    public MTE_BASE_DRBGS_NONCE_MIN_BYTES mte_base_drbgs_nonce_min_bytes;
    public MTE_BASE_DRBGS_NONCE_MAX_BYTES mte_base_drbgs_nonce_max_bytes;
    public MTE_BASE_DRBGS_RESEED_INTERVAL mte_base_drbgs_reseed_interval;
    public MTE_BASE_DRBGS_INCR_INST_ERROR mte_base_drbgs_incr_inst_error;
    public MTE_BASE_DRBGS_INCR_GEN_ERROR mte_base_drbgs_incr_gen_error;
    public MTE_BASE_VERIFIERS_COUNT mte_base_verifiers_count;
    public MTE_BASE_VERIFIERS_NAME mte_base_verifiers_name;
    public MTE_BASE_VERIFIERS_ALGO mte_base_verifiers_algo;
    public MTE_BASE_CIPHERS_COUNT mte_base_ciphers_count;
    public MTE_BASE_CIPHERS_NAME mte_base_ciphers_name;
    public MTE_BASE_CIPHERS_ALGO mte_base_ciphers_algo;
    public MTE_BASE_CIPHERS_BLOCK_BYTES mte_base_ciphers_block_bytes;
    public MTE_BASE_HASHES_COUNT mte_base_hashes_count;
    public MTE_BASE_HASHES_NAME mte_base_hashes_name;
    public MTE_BASE_HASHES_ALGO mte_base_hashes_algo;

    /// <summary>
    /// Load MteBase parts.
    /// </summary>
    private void LoadBase(ILoader l) {
      BindDelegate(l, "mte_base_version", out mte_base_version);
      BindDelegate(l, "mte_wrap_base_version_major",
                   out mte_base_version_major);
      BindDelegate(l, "mte_wrap_base_version_minor",
                   out mte_base_version_minor);
      BindDelegate(l, "mte_wrap_base_version_patch",
                   out mte_base_version_patch);
      BindDelegate(l, "mte_init", out mte_init);
      BindDelegate(l, "mte_license_init", out mte_license_init);
      BindDelegate(l, "mte_wrap_base_status_count", out mte_base_status_count);
      BindDelegate(l, "mte_wrap_base_status_name", out mte_base_status_name);
      BindDelegate(l, "mte_wrap_base_status_description",
                   out mte_base_status_description);
      BindDelegate(l, "mte_wrap_base_status_code", out mte_base_status_code);
      BindDelegate(l, "mte_base_status_is_error", out mte_base_status_is_error);
      BindDelegate(l, "mte_wrap_base_has_runtime_opts",
                   out mte_base_has_runtime_opts);
      BindDelegate(l, "mte_wrap_base_default_drbg", out mte_base_default_drbg);
      BindDelegate(l, "mte_wrap_base_default_tok_bytes",
                   out mte_base_default_tok_bytes);
      BindDelegate(l, "mte_wrap_base_default_verifiers",
                   out mte_base_default_verifiers);
      BindDelegate(l, "mte_wrap_base_default_cipher",
                   out mte_base_default_cipher);
      BindDelegate(l, "mte_wrap_base_default_hash", out mte_base_default_hash);
      BindDelegate(l, "mte_wrap_base_drbgs_count", out mte_base_drbgs_count);
      BindDelegate(l, "mte_wrap_base_drbgs_name", out mte_base_drbgs_name);
      BindDelegate(l, "mte_wrap_base_drbgs_algo", out mte_base_drbgs_algo);
      BindDelegate(l, "mte_wrap_base_drbgs_sec_strength_bytes",
                   out mte_base_drbgs_sec_strength_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_personal_min_bytes",
                   out mte_base_drbgs_personal_min_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_personal_max_bytes",
                   out mte_base_drbgs_personal_max_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_entropy_min_bytes",
                   out mte_base_drbgs_entropy_min_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_entropy_max_bytes",
                   out mte_base_drbgs_entropy_max_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_nonce_min_bytes",
                   out mte_base_drbgs_nonce_min_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_nonce_max_bytes",
                   out mte_base_drbgs_nonce_max_bytes);
      BindDelegate(l, "mte_wrap_base_drbgs_reseed_interval",
                   out mte_base_drbgs_reseed_interval);
      BindDelegate(l, "mte_wrap_base_drbgs_incr_inst_error",
                   out mte_base_drbgs_incr_inst_error);
      BindDelegate(l, "mte_wrap_base_drbgs_incr_gen_error",
                   out mte_base_drbgs_incr_gen_error);
      BindDelegate(l, "mte_wrap_base_verifiers_count",
                   out mte_base_verifiers_count);
      BindDelegate(l, "mte_wrap_base_verifiers_name",
                   out mte_base_verifiers_name);
      BindDelegate(l, "mte_wrap_base_verifiers_algo",
                   out mte_base_verifiers_algo);
      BindDelegate(l, "mte_wrap_base_ciphers_count",
                   out mte_base_ciphers_count);
      BindDelegate(l, "mte_wrap_base_ciphers_name", out mte_base_ciphers_name);
      BindDelegate(l, "mte_wrap_base_ciphers_algo", out mte_base_ciphers_algo);
      BindDelegate(l, "mte_wrap_base_ciphers_block_bytes",
                   out mte_base_ciphers_block_bytes);
      BindDelegate(l, "mte_wrap_base_hashes_count", out mte_base_hashes_count);
      BindDelegate(l, "mte_wrap_base_hashes_name", out mte_base_hashes_name);
      BindDelegate(l, "mte_wrap_base_hashes_algo", out mte_base_hashes_algo);
    }

    /// <summary>
    /// Load parts if they are available.
    /// </summary>
    partial void LoadDec(ILoader l);
    partial void LoadEnc(ILoader l);
    partial void LoadFlenEnc(ILoader l);
    partial void LoadJail(ILoader l);
    partial void LoadMkeDec(ILoader l);
    partial void LoadMkeEnc(ILoader l);

    /// <summary>
    /// Bind the delegate to the given name using the given loader.
    /// </summary>
    private void BindDelegate<TDelegate>(ILoader loader,
                                         string symbol,
                                         out TDelegate del)
      where TDelegate : Delegate {
      // Get the function pointer.
      IntPtr handle = loader.GetSymbol(symbol);
      if (handle == IntPtr.Zero) {
        throw new ArgumentException("MteInteropBase: Failed to find: " +
                                    symbol);
      }

      // Get the delegate for the function pointer.
#if GDFFP_TEMPLATE
      del = Marshal.GetDelegateForFunctionPointer<TDelegate>(handle);
#else
      del = Marshal.GetDelegateForFunctionPointer(handle, typeof(TDelegate))
        as TDelegate;
#endif
    }

    /// <summary>
    /// Library loader interface.
    /// </summary>
    private interface ILoader {
      // Return the symbol or IntPtr.Zero if not found.
      IntPtr GetSymbol(string symbol);

      // Close/unload the library. Returns true if successful, false if not.
      bool Close();
    }

    /// <summary>
    /// Linux library loader.
    /// </summary>
    private class LinuxLoader : ILoader {
      /// <summary>
      /// Construct with the library name.
      /// </summary>
      public LinuxLoader(string libName) {
        // Load the library.
        myLib = Open(libName);
        if (myLib == IntPtr.Zero) {
          libName = "lib" + libName + ".so";
          myLib = Open(libName);
          if (myLib == IntPtr.Zero) {
#if E_CD
            libName = Path.Combine(Environment.CurrentDirectory, libName);
#else
            libName = Path.Combine(Directory.GetCurrentDirectory(), libName);
#endif
            myLib = Open(libName);
            if (myLib == IntPtr.Zero) {
              throw new ArgumentException("LinuxLoader: Failed to load: " +
                                          libName);
            }
          }
        }
      }

      /// <summary>
      /// Interface methods.
      /// </summary>
      public IntPtr GetSymbol(string symbol) {
#if UTF8_MARSHALING
        return dlsym(myLib, symbol);
#else
        byte[] symbol8 = GetUtf8Unshared(symbol);
        return dlsym(myLib, symbol8);
#endif
      }
      public bool Close() {
        return dlclose(myLib) == 0;
      }

      /// <summary>
      /// Open the given file.
      /// </summary>
      private static IntPtr Open(string libName) {
#if UTF8_MARSHALING
        return dlopen(libName, RTLD_NOW);
#else
        byte[] libName8 = GetUtf8Unshared(libName);
        return dlopen(libName8, RTLD_NOW);
#endif
      }

      /// <summary>
      /// Open mode.
      /// </summary>
      private const int RTLD_NOW = 2;

      /// <summary>
      /// Library handle.
      /// </summary>
      private IntPtr myLib;

      /// <summary>
      /// Imports.
      /// </summary>
#if UTF8_MARSHALING
      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlopen([MarshalAs(UnmanagedType.LPUTF8Str)] string filename,
                    int flag);

      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlsym(IntPtr handle,
                   [MarshalAs(UnmanagedType.LPUTF8Str)] string symbol);
#else
      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlopen(byte[] filename, int flag);

      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlsym(IntPtr handle, byte[] symbol);
#endif

      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      int dlclose(IntPtr handle);
    }

    /// <summary>
    /// MacOS library loader.
    /// </summary>
    private class MacOsLoader : ILoader {
      /// <summary>
      /// Construct with the library name.
      /// </summary>
      public MacOsLoader(string libName) {
        // Load the library.
        myLib = Open(libName);
        if (myLib == IntPtr.Zero) {
          libName = "lib" + libName + ".dylib";
          myLib = Open(libName);
          if (myLib == IntPtr.Zero) {
#if E_CD
            libName = Path.Combine(Environment.CurrentDirectory, libName);
#else
            libName = Path.Combine(Directory.GetCurrentDirectory(), libName);
#endif
            myLib = Open(libName);
            if (myLib == IntPtr.Zero) {
              throw new ArgumentException("MacOsLoader: Failed to load: " +
                                          libName);
            }
          }
        }
      }

      /// <summary>
      /// Interface methods.
      /// </summary>
      public IntPtr GetSymbol(string symbol) {
#if UTF8_MARSHALING
        return dlsym(myLib, symbol);
#else
        byte[] symbol8 = GetUtf8Unshared(symbol);
        return dlsym(myLib, symbol8);
#endif
      }
      public bool Close() {
        return dlclose(myLib) == 0;
      }

      /// <summary>
      /// Open the given file.
      /// </summary>
      private static IntPtr Open(string libName) {
#if UTF8_MARSHALING
        return dlopen(libName, RTLD_NOW);
#else
        byte[] libName8 = GetUtf8Unshared(libName);
        return dlopen(libName8, RTLD_NOW);
#endif
      }

      /// <summary>
      /// Open mode.
      /// </summary>
      private const int RTLD_NOW = 2;

      /// <summary>
      /// Library handle.
      /// </summary>
      private IntPtr myLib;

      /// <summary>
      /// Imports.
      /// </summary>
#if UTF8_MARSHALING
      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlopen([MarshalAs(UnmanagedType.LPUTF8Str)] string filename,
                    int flag);

      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlsym(IntPtr handle,
                   [MarshalAs(UnmanagedType.LPUTF8Str)] string symbol);
#else
      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlopen(byte[] filename, int flag);

      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr dlsym(IntPtr handle, byte[] symbol);
#endif

      [DllImport("dl", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      int dlclose(IntPtr handle);
    }

    /// <summary>
    /// Windows library loader.
    /// </summary>
    private class WindowsLoader : ILoader {
      /// <summary>
      /// Construct with the library name.
      /// </summary>
      public WindowsLoader(string libName) {
        // Load the library.
        myLib = LoadLibrary(libName);
        if (myLib == IntPtr.Zero) {
          libName = libName + ".dll";
          myLib = LoadLibrary(libName);
          if (myLib == IntPtr.Zero) {
#if E_CD
            libName = Path.Combine(Environment.CurrentDirectory, libName);
#else
            libName = Path.Combine(Directory.GetCurrentDirectory(), libName);
#endif
            myLib = LoadLibrary(libName);
            if (myLib == IntPtr.Zero) {
              throw new ArgumentException("WindowsLoader: Failed to load: " +
                                          libName);
            }
          }
        }
      }

      /// <summary>
      /// Interface methods.
      /// </summary>
      public IntPtr GetSymbol(string symbol) {
        return GetProcAddress(myLib, symbol);
      }
      public bool Close() {
        return FreeLibrary(myLib);
      }

      /// <summary>
      /// Library handle.
      /// </summary>
      private IntPtr myLib;

      /// <summary>
      /// Imports.
      /// </summary>
      [DllImport("kernel32", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr LoadLibrary(string filename);

      [DllImport("kernel32", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      IntPtr GetProcAddress(IntPtr handle, string symbol);

      [DllImport("kernel32", CallingConvention = CallingConvention.Cdecl)]
      private static extern
      bool FreeLibrary(IntPtr handle);
    }

    /// <summary>
    /// Library loader.
    /// </summary>
    private ILoader myLoader;

    /// <summary>
    /// Add-ons.
    /// </summary>
    private bool myHasFlen = false;
    private bool myHasJail = false;
    private bool myHasMke = false;

#if !UTF8_MARSHALING
    /// <summary>
    /// Buffer for UTF-8 conversion.
    /// </summary>
    byte[] myUtf8 = new byte[1];
#endif
  }
}
#pragma warning restore 1591

