// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <auto-generated />
#pragma warning disable 1591

using Eclypses.MTE.Interop;
using System;

namespace Eclypses.MTE {
  /// <summary>
  /// Class MteJail
  ///
  /// This is a helper to mutate the nonce according to the chosen algorithm.
  /// </summary>
  public class MteJail : MteNonceCallback {
    /// <summary>
    /// This defines the jailbreak detection algorithm to use or simulate.
    /// </summary>
    public enum Algo {
      /// <summary>
      /// No choice made.
      /// </summary>
      aNone,

      /// <summary>
      /// Android ARM32 device.
      /// </summary>
      aAndroidArm32Dev,

      /// <summary>
      /// Android ARM64 device.
      /// </summary>
      aAndroidArm64Dev,

      /// <summary>
      /// Android x86 simulator.
      /// </summary>
      aAndroidX86Sim,

      /// <summary>
      /// Android x86_64 simulator.
      /// </summary>
      aAndroidX86_64Sim,

      /// <summary>
      /// iOS ARM64 device.
      /// </summary>
      aIosArm64Dev,

      /// <summary>
      /// iOS x86_64 simulator.
      /// </summary>
      aIosX86_64Sim
    }

    /// <summary>
    /// Constructor using a provided interop.
    /// </summary>
    public MteJail(MteInterop interop) {
      myInterop = interop;
    }

    /// <summary>
    /// Set the jailbreak algorithm to pair with. Defaults to Algo.aNone.
    /// </summary>
    public void SetAlgo(Algo algo) {
      myAlgo = algo;
    }

    /// <summary>
    /// Set the nonce seed.
    /// </summary>
    public void SetNonceSeed(UInt64 seed) {
      for (int i = 0; i < sizeof(UInt64); ++i) {
        mySeed[i] = (byte)(seed >> (i * 8));
      }
    }

    /// <summary>
    /// The nonce callback.
    /// </summary>
    public virtual void NonceCallback(int minLength,
                                      int maxLength,
                                      byte[] nonce,
                                      out int nBytes) {
      UInt32 nb = 0;
      switch (myAlgo) {
        case Algo.aNone:
          int amt = Math.Min(mySeed.Length, maxLength);
          if (amt != 0) {
            Array.Copy(nonce, mySeed, amt);
          }
          nb = (UInt32)Math.Max(amt, minLength);
          break;

        case Algo.aAndroidArm32Dev:
          myInterop.mte_jail_n_cb_android_arm32_d(mySeed,
                                                  (UInt32)mySeed.Length,
                                                  (UInt32)minLength,
                                                  (UInt32)maxLength,
                                                  nonce,
                                                  out nb);
          break;

        case Algo.aAndroidArm64Dev:
          myInterop.mte_jail_n_cb_android_arm64_d(mySeed,
                                                  (UInt32)mySeed.Length,
                                                  (UInt32)minLength,
                                                  (UInt32)maxLength,
                                                  nonce,
                                                  out nb);
          break;

        case Algo.aAndroidX86Sim:
          myInterop.mte_jail_n_cb_android_x86_s(mySeed,
                                                (UInt32)mySeed.Length,
                                                (UInt32)minLength,
                                                (UInt32)maxLength,
                                                nonce,
                                                out nb);
          break;

        case Algo.aAndroidX86_64Sim:
          myInterop.mte_jail_n_cb_android_x86_64_s(mySeed,
                                                   (UInt32)mySeed.Length,
                                                   (UInt32)minLength,
                                                   (UInt32)maxLength,
                                                   nonce,
                                                   out nb);
          break;

        case Algo.aIosArm64Dev:
          myInterop.mte_jail_n_cb_ios_arm64_d(mySeed,
                                              (UInt32)mySeed.Length,
                                              (UInt32)minLength,
                                              (UInt32)maxLength,
                                              nonce,
                                              out nb);
          break;

        case Algo.aIosX86_64Sim:
          myInterop.mte_jail_n_cb_ios_x86_64_s(mySeed,
                                               (UInt32)mySeed.Length,
                                               (UInt32)minLength,
                                               (UInt32)maxLength,
                                               nonce,
                                               out nb);
          break;
      }
      nBytes = (int)nb;
    }

    /// <summary>
    /// Jailbreak algorithm.
    /// </summary>
    private Algo myAlgo = Algo.aNone;

    /// <summary>
    /// Nonce seed.
    /// </summary>
    private byte[] mySeed = new byte[sizeof(UInt64)];

    /// <summary>
    /// Interop.
    /// </summary>
    private MteInterop myInterop;
  }
}
#pragma warning restore 1591

