// The MIT License (MIT)
//
// Copyright (c) Eclypses, Inc.
//
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Determine if UTF-8 marshaling is supported.
#if !NETCOREAPP1_0 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETSTANDARD2_0 && !NET11 && !NET20 && !NET35 && !NET40 && !NET403 && !NET45 && !NET451 && !NET452 && !NET46 && !NET461 && !NET462 && !NET47
#define UTF8_MARSHALING
#endif

// <auto-generated />
#pragma warning disable 1591

using Eclypses.MTE.Interop;
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Eclypses.MTE {
  /// <summary>
  /// Class MteMkeDec
  ///
  /// This is the MTE Managed-Key Encryption decoder.
  ///
  /// To use, create an object of this type, call Instantiate(), call Decode()
  /// zero or more times to decode/decrypt each encoded/encrypted data, then
  /// optionally call Uninstantiate() to clear the random state.
  ///
  /// Alternatively, the state can be saved any time after Instantiate() and
  /// restored instead of Instantiate() to pick up at a known point.
  ///
  /// To use as a chunk-based decryptor, call StartDecrypt(), call
  /// DecryptChunk() zero or more times to decrypt each chunk of data, then
  /// FinishDecrypt().
  /// </summary>
  public class MteMkeDec : MteBase, IMteMkeDec {
    /// <summary>
    /// Constructor using default options. The default interop is used.
    ///
    /// The timestamp window and sequence window are optionally settable.
    /// </summary>
    public MteMkeDec(UInt64 tWindow = 0, Int32 sWindow = 0) : this(null,
                                                                   tWindow,
                                                                   sWindow) { }

    /// <summary>
    /// Constructor using default options. The provided interop is used.
    ///
    /// The timestamp window and sequence window are optionally settable.
    /// </summary>
    public MteMkeDec(MteInterop interop,
                     UInt64 tWindow = 0,
                     Int32 sWindow = 0) : base(interop) {
      Init(GetDefaultDrbg(), GetDefaultTokBytes(), GetDefaultVerifiers(),
           GetDefaultCipher(), GetDefaultHash(), tWindow, sWindow);
    }

    /// <summary>
    /// Constructor taking the DRBG, token size in bytes, verifiers algorithm,
    /// cipher algorithm, hash algorithm, timestamp window, and sequence window.
    /// The default interop is used.
    /// </summary>
    public MteMkeDec(MteDrbgs drbg,
                     int tokBytes,
                     MteVerifiers verifiers,
                     MteCiphers cipher,
                     MteHashes hash,
                     UInt64 tWindow,
                     Int32 sWindow) : this(null,
                                           drbg,
                                           tokBytes,
                                           verifiers,
                                           cipher,
                                           hash,
                                           tWindow,
                                           sWindow) { }

    /// <summary>
    /// Constructor taking a provided interop, the DRBG, token size in bytes,
    /// verifiers algorithm, cipher algorithm, hash algorithm, timestamp window,
    /// and sequence window.
    /// </summary>
    public MteMkeDec(MteInterop interop,
                     MteDrbgs drbg,
                     int tokBytes,
                     MteVerifiers verifiers,
                     MteCiphers cipher,
                     MteHashes hash,
                     UInt64 tWindow,
                     Int32 sWindow) : base(interop) {
      Init(drbg, tokBytes, verifiers, cipher, hash, tWindow, sWindow);
    }

    /// <summary>
    /// Destructor. The Uninstantiate() method is called.
    /// </summary>
    ~MteMkeDec() {
      // Uninstantiate if constructed fully.
      if (myDecoder != IntPtr.Zero) {
        Uninstantiate();
      }

      // Deallocate the handles.
      if (myDecoderHandle.IsAllocated) {
        myDecoderHandle.Free();
      }
      if (myDecHandle.IsAllocated) {
        myDecHandle.Free();
      }
      if (mySaveHandle.IsAllocated) {
        mySaveHandle.Free();
      }
      if (mySaveHandle64.IsAllocated) {
        mySaveHandle64.Free();
      }
      if (myDecryptorHandle.IsAllocated) {
        myDecryptorHandle.Free();
      }
    }

    /// <summary>
    /// Initialize the decoder with the personalization string. The entropy and
    /// nonce callbacks will be called to get the rest of the seeding material.
    /// Returns the status.
    /// </summary>
    public MteStatus Instantiate(byte[] ps) {
      return myInterop.mte_mke_dec_instantiate(myDecoder,
                                               myEntropyCb, IntPtr.Zero,
                                               myNonceCb, IntPtr.Zero,
                                               ps, (UInt32)ps.Length);
    }

    /// <summary>
    /// Initialize the decoder with the personalization string. The entropy and
    /// nonce callbacks will be called to get the rest of the seeding material.
    /// Returns the status.
    /// </summary>
    public MteStatus Instantiate(string ps) {
      return Instantiate(Encoding.UTF8.GetBytes(ps));
    }

    /// <summary>
    /// Returns the reseed counter.
    /// </summary>
    public UInt64 GetReseedCounter() {
      return myInterop.mte_mke_dec_reseed_counter(myDecoder);
    }

    /// <summary>
    /// Returns the saved state. On error, null is returned.
    /// </summary>
    public byte[] SaveState() {
      MteStatus status =
        myInterop.mte_mke_dec_state_save(myDecoder, mySave);
      return status == MteStatus.mte_status_success ? mySaveBuff : null;
    }

    /// <summary>
    /// Returns the Base64-encoded saved state. On error, null is returned.
    /// </summary>
    public string SaveStateB64() {
      MteStatus status =
        myInterop.mte_mke_dec_state_save_b64(myDecoder, mySave64);
      return status == MteStatus.mte_status_success ? GetCString(mySaveBuff64) :
                                                      null;
    }

    /// <summary>
    /// Restore a saved state, which must be the same length as was returned
    /// from the SaveState() call. Returns the status.
    /// </summary>
    public MteStatus RestoreState(byte[] saved) {
      return myInterop.mte_mke_dec_state_restore(myDecoder, saved);
    }

    /// <summary>
    /// Restore a saved state, which must be the same length as was returned
    /// from the SaveStateB64() call. Returns the status.
    /// </summary>
    public MteStatus RestoreStateB64(string saved) {
#if UTF8_MARSHALING
      return myInterop.mte_mke_dec_state_restore_b64(myDecoder, saved);
#else
      byte[] saved8 = myInterop.GetUtf8(saved);
      return myInterop.mte_mke_dec_state_restore_b64(myDecoder, saved8);
#endif
    }

    /// <summary>
    /// Returns the decode buffer size in bytes given the encoded data length
    /// in bytes.
    /// </summary>
    public int GetBuffBytes(int encBytes) {
      return (int)myInterop.mte_mke_dec_buff_bytes(myDecoder, (UInt32)encBytes);
    }

    /// <summary>
    /// Returns the decode buffer size in bytes given the encoded data length
    /// in bytes.
    /// </summary>
    public int GetBuffBytesB64(int encBytes) {
      return (int)myInterop.mte_mke_dec_buff_bytes_b64(myDecoder,
                                                       (UInt32)encBytes);
    }

    /// <summary>
    /// Decode the given encoded version. Returns the decoded data and sets
    /// status to the status.
    /// </summary>
    public byte[] Decode(byte[] encoded, out MteStatus status) {
      // Get the decode buffer requirement and resize if necessary.
      int buffBytes = GetBuffBytes(encoded.Length);
      if (buffBytes > myDecBuff.Length) {
        if (myDecHandle.IsAllocated) {
          myDecHandle.Free();
        }
        myDecBuff = new byte[buffBytes];
        myDecHandle = GCHandle.Alloc(myDecBuff, GCHandleType.Pinned);
        myDec = myDecHandle.AddrOfPinnedObject();
      }
      else if (buffBytes == 0) {
        status = MteStatus.mte_status_invalid_input;
        return null;
      }

      // Decode.
      UInt32 dOff;
      UInt32 dBytes;
      status = myInterop.mte_mke_dec_decode_a(myDecoder,
                                              myTimestampCb, IntPtr.Zero,
                                              encoded, (UInt32)encoded.Length,
                                              myDec, out dOff, out dBytes,
                                              out myEncTs,
                                              out myDecTs,
                                              out myMsgSkipped);
      if (StatusIsError(status)) {
        return null;
      }

      // Return the decoded part.
      byte[] decoded = new byte[(int)dBytes];
      Array.Copy(myDecBuff, (int)dOff, decoded, 0, (int)dBytes);
      return decoded;
    }

    /// <summary>
    /// Decode the given encoded version. Returns the decoded data and sets
    /// status to the status.
    /// </summary>
    public byte[] DecodeB64(string encoded, out MteStatus status) {
      // Get the decode buffer requirement and resize if necessary.
      int buffBytes = GetBuffBytesB64(encoded.Length);
      if (buffBytes > myDecBuff.Length) {
        if (myDecHandle.IsAllocated) {
          myDecHandle.Free();
        }
        myDecBuff = new byte[buffBytes];
        myDecHandle = GCHandle.Alloc(myDecBuff, GCHandleType.Pinned);
        myDec = myDecHandle.AddrOfPinnedObject();
      }

      // Decode.
      UInt32 dOff;
      UInt32 dBytes;
#if UTF8_MARSHALING
      status = myInterop.mte_mke_dec_decode_b64_s(myDecoder,
                                                  myTimestampCb,
                                                  IntPtr.Zero,
                                                  encoded,
                                                  (UInt32)encoded.Length,
                                                  myDec, out dOff, out dBytes,
                                                  out myEncTs,
                                                  out myDecTs,
                                                  out myMsgSkipped);
#else
      byte[] encoded8 = Encoding.UTF8.GetBytes(encoded);
      status = myInterop.mte_mke_dec_decode_b64_s(myDecoder,
                                                  myTimestampCb,
                                                  IntPtr.Zero,
                                                  encoded8,
                                                  (UInt32)encoded8.Length,
                                                  myDec, out dOff, out dBytes,
                                                  out myEncTs,
                                                  out myDecTs,
                                                  out myMsgSkipped);
#endif
      if (StatusIsError(status)) {
        return null;
      }

      // Return the decoded part.
      byte[] decoded = new byte[(int)dBytes];
      Array.Copy(myDecBuff, (int)dOff, decoded, 0, (int)dBytes);
      return decoded;
    }

    /// <summary>
    /// Decode the given message to a string. Returns the decoded string and
    /// sets status to the MTE status.
    /// </summary>
    public string DecodeStr(byte[] encoded, out MteStatus status) {
      // Get the decode buffer requirement and resize if necessary.
      int buffBytes = GetBuffBytes(encoded.Length);
      if (buffBytes > myDecBuff.Length) {
        if (myDecHandle.IsAllocated) {
          myDecHandle.Free();
        }
        myDecBuff = new byte[buffBytes];
        myDecHandle = GCHandle.Alloc(myDecBuff, GCHandleType.Pinned);
        myDec = myDecHandle.AddrOfPinnedObject();
      }
      else if (buffBytes == 0) {
        status = MteStatus.mte_status_invalid_input;
        return null;
      }

      // Decode.
      UInt32 dOff;
      UInt32 dBytes;
      status = myInterop.mte_mke_dec_decode_a(myDecoder,
                                              myTimestampCb, IntPtr.Zero,
                                              encoded, (UInt32)encoded.Length,
                                              myDec, out dOff, out dBytes,
                                              out myEncTs,
                                              out myDecTs,
                                              out myMsgSkipped);
      if (StatusIsError(status)) {
        return null;
      }

      // Return the decoded part as a string.
      return GetCString(myDecBuff, (int)dOff);
    }

    /// <summary>
    /// Decode the given message to a string. Returns the decoded string and
    /// sets status to the MTE status.
    /// </summary>
    public string DecodeStrB64(string encoded, out MteStatus status) {
      // Get the decode buffer requirement and resize if necessary.
      int buffBytes = GetBuffBytesB64(encoded.Length);
      if (buffBytes > myDecBuff.Length) {
        if (myDecHandle.IsAllocated) {
          myDecHandle.Free();
        }
        myDecBuff = new byte[buffBytes];
        myDecHandle = GCHandle.Alloc(myDecBuff, GCHandleType.Pinned);
        myDec = myDecHandle.AddrOfPinnedObject();
      }

      // Decode.
      UInt32 dOff;
      UInt32 dBytes;
#if UTF8_MARSHALING
      status = myInterop.mte_mke_dec_decode_b64_s(myDecoder,
                                                  myTimestampCb, IntPtr.Zero,
                                                  encoded,
                                                  (UInt32)encoded.Length,
                                                  myDec, out dOff, out dBytes,
                                                  out myEncTs,
                                                  out myDecTs,
                                                  out myMsgSkipped);
#else
      byte[] encoded8 = Encoding.UTF8.GetBytes(encoded);
      status = myInterop.mte_mke_dec_decode_b64_s(myDecoder,
                                                  myTimestampCb, IntPtr.Zero,
                                                  encoded8,
                                                  (UInt32)encoded8.Length,
                                                  myDec, out dOff, out dBytes,
                                                  out myEncTs,
                                                  out myDecTs,
                                                  out myMsgSkipped);
#endif
      if (StatusIsError(status)) {
        return null;
      }

      // Return the decoded part as a string.
      return GetCString(myDecBuff, (int)dOff);
    }

    /// <summary>
    /// Decode the given encoded version of the given length at the given offset
    /// to the given buffer at the given offset. Returns the status. Sets decOff
    /// to the offset of the decoded version. Sets decBytes to the decoded
    /// length in bytes. The decoded buffer must have sufficient length
    /// remaining after the offset. Use GetBuffBytes() to determine the buffer
    /// requirement.
    /// </summary>
    public MteStatus Decode(byte[] encoded, int encOff, int encBytes,
                            byte[] decoded, ref int decOff, out int decBytes) {
      // Pin the encoded array. Get a pointer to the offset.
      GCHandle encHandle = GCHandle.Alloc(encoded, GCHandleType.Pinned);
      IntPtr encPtr = Marshal.UnsafeAddrOfPinnedArrayElement(encoded, encOff);

      // Pin the decoded array. Get a pointer to the offset.
      GCHandle decHandle = GCHandle.Alloc(decoded, GCHandleType.Pinned);
      IntPtr decPtr = Marshal.UnsafeAddrOfPinnedArrayElement(decoded, decOff);

      // Decode.
      UInt32 dOff;
      UInt32 dBytes;
      MteStatus status = myInterop.mte_mke_dec_decode_p(myDecoder,
                                                        myTimestampCb,
                                                        IntPtr.Zero,
                                                        encPtr,
                                                        (UInt32)encBytes,
                                                        decPtr,
                                                        out dOff, out dBytes,
                                                        out myEncTs,
                                                        out myDecTs,
                                                        out myMsgSkipped);
      decOff += (int)dOff;
      decBytes = (int)dBytes;

      // Unpin the arrays.
      encHandle.Free();
      decHandle.Free();

      // Return status.
      return status;
    }

    /// <summary>
    /// Decode the given encoded version of the given length at the given offset
    /// to the given buffer at the given offset. Returns the status. Sets decOff
    /// to the offset of the decoded version. Sets decBytes to the decoded
    /// length in bytes. The decoded buffer must have sufficient length
    /// remaining after the offset. Use GetBuffBytesB64() to determine the
    /// buffer requirement.
    /// </summary>
    public MteStatus DecodeB64(byte[] encoded, int encOff, int encBytes,
                               byte[] decoded,
                               ref int decOff,
                               out int decBytes) {
      // Pin the encoded array. Get a pointer to the offset.
      GCHandle encHandle = GCHandle.Alloc(encoded, GCHandleType.Pinned);
      IntPtr encPtr = Marshal.UnsafeAddrOfPinnedArrayElement(encoded, encOff);

      // Pin the decoded array. Get a pointer to the offset.
      GCHandle decHandle = GCHandle.Alloc(decoded, GCHandleType.Pinned);
      IntPtr decPtr = Marshal.UnsafeAddrOfPinnedArrayElement(decoded, decOff);

      // Decode.
      UInt32 dOff;
      UInt32 dBytes;
      MteStatus status = myInterop.mte_mke_dec_decode_b64_p(myDecoder,
                                                            myTimestampCb,
                                                            IntPtr.Zero,
                                                            encPtr,
                                                            (UInt32)encBytes,
                                                            decPtr,
                                                            out dOff,
                                                            out dBytes,
                                                            out myEncTs,
                                                            out myDecTs,
                                                            out myMsgSkipped);
      decOff += (int)dOff;
      decBytes = (int)dBytes;

      // Unpin the arrays.
      encHandle.Free();
      decHandle.Free();

      // Return status.
      return status;
    }

    /// <summary>
    /// Start a chunk-based decryption session. Returns the status.
    /// </summary>
    public MteStatus StartDecrypt() {
      // Start the decrypt session.
      return myInterop.mte_mke_dec_decrypt_start(myDecoder, myDecryptor);
    }

    /// <summary>
    /// Decrypt a chunk of data in a chunk-based decryption session. Returns the
    /// decrypted data. Returns null on error.
    /// </summary>
    public byte[] DecryptChunk(byte[] encrypted) {
      // Resize the buffer if necessary.
      int buffBytes = encrypted.Length + myCiphBlockBytes;
      if (buffBytes > myDecBuff.Length) {
        if (myDecHandle.IsAllocated) {
          myDecHandle.Free();
        }
        myDecBuff = new byte[buffBytes];
        myDecHandle = GCHandle.Alloc(myDecBuff, GCHandleType.Pinned);
        myDec = myDecHandle.AddrOfPinnedObject();
      }

      // Decrypt the chunk.
      UInt32 dBytes;
      MteStatus status = myInterop.mte_mke_dec_decrypt_chunk_a(myDecoder,
                                                       myDecryptor,
                                                       encrypted,
                                                       (UInt32)encrypted.Length,
                                                       myDec, out dBytes);

      // Return the decrypted part.
      byte[] decrypted = new byte[dBytes];
      Array.Copy(myDecBuff, decrypted, (int)dBytes);
      return status == MteStatus.mte_status_success ? decrypted : null;
    }

    /// <summary>
    /// Decrypt a chunk of data at the given offset of the given length in a
    /// chunk-based decryption session. Some decrypted data is written to the
    /// decrypted buffer starting at decOff. The amount decrypted is returned.
    /// Returns -1 on error.
    /// </summary>
    public int DecryptChunk(byte[] encrypted, int encOff, int encBytes,
                            byte[] decrypted, int decOff) {
      // Pin the encrypted array. Get a pointer to the offset.
      GCHandle encHandle = GCHandle.Alloc(encrypted, GCHandleType.Pinned);
      IntPtr encPtr = Marshal.UnsafeAddrOfPinnedArrayElement(encrypted, encOff);

      // Pin the decrypted array. Get a pointer to the offset.
      GCHandle decHandle = GCHandle.Alloc(decrypted, GCHandleType.Pinned);
      IntPtr decPtr = Marshal.UnsafeAddrOfPinnedArrayElement(decrypted, decOff);

      // Decrypt the chunk.
      UInt32 dBytes;
      MteStatus status = myInterop.mte_mke_dec_decrypt_chunk_p(myDecoder,
                                                               myDecryptor,
                                                               encPtr,
                                                               (UInt32)encBytes,
                                                               decPtr,
                                                               out dBytes);

      // Unpin the arrays.
      encHandle.Free();
      decHandle.Free();

      // Return the amount decrypted.
      return status == MteStatus.mte_status_success ? (int)dBytes : -1;
    }

    /// <summary>
    /// Finish a chunk-based decryption session. Returns the final part of the
    /// result and sets status to the status.
    /// </summary>
    public byte[] FinishDecrypt(out MteStatus status) {
      // Finish the decrypt session.
      UInt32 dOff = 0;
      UInt32 dBytes;
      status = myInterop.mte_mke_dec_decrypt_finish(myDecoder, myDecryptor,
                                                    myTimestampCb, IntPtr.Zero,
                                                    out dOff, out dBytes,
                                                    out myEncTs,
                                                    out myDecTs,
                                                    out myMsgSkipped);
      if (StatusIsError(status)) {
        return null;
      }

      // Return the final decrypted data.
      byte[] decrypted = new byte[dBytes];
      Array.Copy(myDecryptorBuff, (int)dOff, decrypted, 0, (int)dBytes);
      return decrypted;
    }

    /// <summary>
    /// Finish a chunk-based decryption session. Writes the final part of the
    /// result to the decrypted buffer starting at off. Sets bytes to the length
    /// of the result in bytes. Returns the status. The decrypted buffer must be
    /// large enough to hold at least the chosen cipher's block size in the mode
    /// of operation.
    /// </summary>
    public MteStatus FinishDecrypt(byte[] decrypted, int off, out int bytes) {
      // Finish the decrypt session.
      UInt32 dOff;
      UInt32 dBytes;
      MteStatus status = myInterop.mte_mke_dec_decrypt_finish(myDecoder,
                                                              myDecryptor,
                                                              myTimestampCb,
                                                              IntPtr.Zero,
                                                              out dOff,
                                                              out dBytes,
                                                              out myEncTs,
                                                              out myDecTs,
                                                              out myMsgSkipped);
      if (StatusIsError(status)) {
        bytes = 0;
        return status;
      }

      // Copy the final decrypted data.
      bytes = (int)dBytes;
      if (bytes != 0) {
        Array.Copy(myDecryptorBuff, (int)dOff, decrypted, off, bytes);
      }

      // Return the status.
      return status;
    }

    /// <summary>
    /// Returns the timestamp set during encoding or 0 if there is no
    /// timestamp.
    /// </summary>
    public UInt64 GetEncTs() {
      return myEncTs;
    }

    /// <summary>
    /// Returns the timestamp set during decoding or 0 if there is no
    /// timestamp.
    /// </summary>
    public UInt64 GetDecTs() {
      return myDecTs;
    }

    /// <summary>
    /// Returns the number of messages that were skipped to get in sync
    /// during the decode or 0 if there is no sequencing.
    /// </summary>
    public UInt32 GetMsgSkipped() {
      return myMsgSkipped;
    }

    /// <summary>
    /// Uninstantiate the decoder. It is no longer usable after this call.
    /// Returns the status.
    /// </summary>
    public MteStatus Uninstantiate() {
      return myInterop.mte_mke_dec_uninstantiate(myDecoder);
    }

    /// <summary>
    /// Initialize.
    /// </summary>
    private void Init(MteDrbgs drbg,
                      int tokBytes,
                      MteVerifiers verifiers,
                      MteCiphers cipher,
                      MteHashes hash,
                      UInt64 tWindow,
                      Int32 sWindow) {
      // Initialize the base.
      InitBase(drbg, tokBytes, verifiers, cipher, hash);

      // Get the decoder size.
      int bytes = (int)myInterop.mte_mke_dec_state_bytes(drbg,
                                                         (UInt32)tokBytes,
                                                         verifiers,
                                                         cipher,
                                                         hash);
      if (bytes == 0) {
        throw new ArgumentOutOfRangeException("MteMkeDec: Invalid options.");
      }

      // Allocate the decoder and pin it to create a handle.
      myDecoderBuff = new byte[bytes];
      myDecoderHandle = GCHandle.Alloc(myDecoderBuff, GCHandleType.Pinned);
      myDecoder = myDecoderHandle.AddrOfPinnedObject();

      // Create the callbacks.
      myEntropyCb = new ENTROPY_CALLBACK(this.MteBaseEntropyCallback);
      myNonceCb = new NONCE_CALLBACK(this.MteBaseNonceCallback);
      myTimestampCb = new TIMESTAMP_CALLBACK(this.MteBaseTimestampCallback);

      // Initialize the decoder state.
      MteStatus status = myInterop.mte_mke_dec_state_init(myDecoder,
                                                          drbg,
                                                          (UInt32)tokBytes,
                                                          verifiers,
                                                          cipher,
                                                          hash,
                                                          tWindow,
                                                          sWindow);
      if (status != MteStatus.mte_status_success) {
        throw new ArgumentOutOfRangeException("MteMkeDec: Invalid options.");
      }

      // Allocate the save buffers.
      mySaveBuff = new byte[myInterop.mte_mke_dec_save_bytes(myDecoder)];
      mySaveBuff64 = new byte[myInterop.mte_mke_dec_save_bytes_b64(myDecoder)];
      mySaveHandle = GCHandle.Alloc(mySaveBuff, GCHandleType.Pinned);
      mySaveHandle64 = GCHandle.Alloc(mySaveBuff64, GCHandleType.Pinned);
      mySave = mySaveHandle.AddrOfPinnedObject();
      mySave64 = mySaveHandle64.AddrOfPinnedObject();

      // Allocate the decryptor state.
      myDecryptorBuff =
        new byte[myInterop.mte_mke_dec_decrypt_state_bytes(myDecoder)];
      myDecryptorHandle = GCHandle.Alloc(myDecryptorBuff, GCHandleType.Pinned);
      myDecryptor = myDecryptorHandle.AddrOfPinnedObject();
      myCiphBlockBytes = GetCiphersBlockBytes(cipher);
      if (myCiphBlockBytes == 0) {
        throw new ArgumentOutOfRangeException("MteMkeDec: Invalid options.");
      }
    }

    /// <summary>
    /// The decoder state.
    /// </summary>
    private IntPtr myDecoder;
    private byte[] myDecoderBuff;
    private GCHandle myDecoderHandle;

    /// <summary>
    /// Decoder buffer.
    /// </summary>
    private IntPtr myDec;
    private byte[] myDecBuff = new byte[0];
    private GCHandle myDecHandle;

    /// <summary>
    /// State save buffer.
    /// </summary>
    private IntPtr mySave;
    private IntPtr mySave64;
    private byte[] mySaveBuff;
    private byte[] mySaveBuff64;
    private GCHandle mySaveHandle;
    private GCHandle mySaveHandle64;

    /// <summary>
    /// Decrypt state.
    /// </summary>
    private IntPtr myDecryptor;
    private byte[] myDecryptorBuff;
    private GCHandle myDecryptorHandle;
    private int myCiphBlockBytes;

    /// <summary>
    /// Callback delegates.
    /// </summary>
    private ENTROPY_CALLBACK myEntropyCb;
    private NONCE_CALLBACK myNonceCb;
    private TIMESTAMP_CALLBACK myTimestampCb;

    /// <summary>
    /// Decode values.
    /// </summary>
    private UInt64 myEncTs;
    private UInt64 myDecTs;
    private UInt32 myMsgSkipped;
  }
}
#pragma warning restore 1591

